### PR TITLE
[GEODE-1887] #comment Fix for Client PROXY region should delegate all operations to server

### PR DESCRIPTION
**Pull request by davinash**
Fix for Client PROXY region should delegate all operations to server
- Resubmitting the PR.
- Separated the Test
- Ran Precheckin and no failures.

### CODE REVIEW

**Comment by fredkrone** [comment]
Totally understand this fix but we are recommending not changing size() functionality as it might break current expected behavior.   However adding a new .serverSize() or .localSize() would be non breaking.  We also plan on addressing these client/server API issues in a new client.

**Comment by metatype** [comment]
^^^ Changing _we_ to _I_ in above comment, because we all come to the project as individual contributors :-)

**Comment by dschneider-pivotal** [comment]
I think this pull request should be closed. GEODE-1887 will be updated with a plan for doing it without breaking backwards compatibility.

**Comment by davinash** [comment]
closing this PR as per the comment above.

**Pull request closed without merging**
