### PR TITLE
GEODE-7714: add disabling stats-archive-file

### PR DESCRIPTION
**Pull request by mkevo**
Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [x] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [x] Is your initial contribution a single, squashed commit?

- [x] Does `gradlew build` run cleanly?

- [x] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, check Concourse for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by davebarnes97** [comment]
@mkevo Do I understand correctly that setting the filename to the empty string `""` will now disable writing stats to a file? Formatting of the JIRA description may have deleted quote marks, so just double-checking.

**Comment by mkevo** [comment]
> @mkevo Do I understand correctly that setting the filename to the empty string `""` will now disable writing stats to a file? Formatting of the JIRA description may have deleted quote marks, so just double-checking.

To disable writing stats to file you can use this two options:

alter runtime --statistic-archive-file=
alter runtime --statistic-archive-file=""

**Comment by mkevo** [comment]
As _alter runtime_ command go through all parameters and check it, in case we don't specified any parameters some commands like `alter runtime --member=server` will be successful. So I made a change to accept only file names that has _.gfs_ suffix. To disable it just provide some random string without _.gfs_.

**Comment by davebarnes97** [comment]
@mkevo If the change you describe is a response to my comment on the JIRA ticket, thanks. To keep all discussion in a single location, I'll summarize my comment here:
  I am uncomfortable with the syntax `alter runtime --statistic-archive-file=` where no value follows 
  the equals sign. I would like to see comments from the Apache Geode developers' mailing list on this 
  proposal.
However, I am also uncomfortable with this latest change. If I understand it correctly, to enable this property, the value following the equals sign must be a filename with one of two suffixes: '.gfs' or '.gz'. Any other string disables the archive-to-a-file function.
I find this counterintuitive. In my opinion:
The simplest way to add a turn-off function to this existing property would be to specify an empty string, using a syntax you suggested earlier: `alter runtime --statistic-archive-file=""`.
If that isn't workable, then (again, my opinion) the next best approach would be to add a boolean option that sets statistics archiving to 'true' or 'false'. 
Again, I would like to see this put to the dev list for additional thoughts.

**Comment by mkevo** [comment]
Hi @davebarnes97,
is it OK to close this PR and open a new one with doc change on this part:
`The file to which the running system member writes statistic samples. For example: “StatisticsArchiveFile.gfs”. An empty string disables archiving. Adding .gz suffix to the file name causes it to be compressed.`

to

`The file to which the running system member writes statistic samples. For example: “StatisticsArchiveFile.gfs”. To disable archiving set it to /dev/null. Adding .gz suffix to the file name causes it to be compressed.`

**Comment by davebarnes97** [comment]
+1 OK with me

**Pull request closed without merging**
