### PR TITLE
GEODE-7967: User Guide - gfsh start locator - reformat oversize table

### PR DESCRIPTION
**Pull request by alb3rtobr**
Fix format issues in the start command page of the user guide.
`start locator` and `start server` command tables have been transformed from html to markdown format. Also, some html tags have been substituted by markdown tags.

### CODE REVIEW

**Comment by davebarnes97** [comment]
Thanks for your contribution, @alb3rtobr. Just a note to let you know that due to schedule pressures, it may be a few days before I'm able to complete my review. Apologies for any inconvenience.

**Review by davebarnes97 — CHANGES_REQUESTED** [review]
Very nice - thanks!
I would like to request a change to be repeated in four locations, where an option name wraps between the double-hyphen and the name. The remedy is to replace the two hyphens with a pair of non-breaking hyphens. I've attached a git diff that shows where the changes are needed.
[PR6552-diff.txt](https://github.com/apache/geode/files/6671802/PR6552-diff.txt)

**Comment by alb3rtobr** [comment]
> Very nice - thanks!
> I would like to request a change to be repeated in four locations, where an option name wraps between the double-hyphen and the name. The remedy is to replace the two hyphens with a pair of non-breaking hyphens. I've attached a git diff that shows where the changes are needed.
> [PR6552-diff.txt](https://github.com/apache/geode/files/6671802/PR6552-diff.txt)

Thanks for the fix @davebarnes97 , I didnt know about these non-breaking hyphens

**Review by davebarnes97 — APPROVED** [review]
+1 LGTM

**Pull request merged**
