### PR TITLE
[GEODE-252] Remove deprecated PartitionAttributes methods

### PR DESCRIPTION
**Pull request by shroman**

### CODE REVIEW

**Comment by upthewaterspout** [comment]
Looks good! I noticed you left in the localProperties and globalProperties fields on PartitionAttributesImpl, as well as leaving the toData/fromData methods alone in that class. Was that to avoid breaking serialization compatibility?

**Comment by shroman** [comment]
Yes, I was not sure it is safe. I updated it.

**Comment by upthewaterspout** [comment]
Ok, looks good. I will run some tests and merge this.

**Comment by upthewaterspout** [comment]
I hit some failures with these changes. I think these related to tests that are using these features that probably need to get fixed.

com.gemstone.gemfire.cache30.CacheXml45DUnitTest.testPartitionedRegionXML
com.gemstone.gemfire.codeAnalysis.AnalyzeSerializablesJUnitTest.testDataSerializables
com.gemstone.gemfire.internal.cache.PartitionedRegionCacheXMLExampleDUnitTest.testExampleWithSubRegion
com.gemstone.gemfire.internal.cache.PartitionedRegionCreationDUnitTest.testTotalNumberOfBuckets

The AnalyzeSerializables is failing because it detected a change to a serializable class. I think since we are breaking backwards compatibility with older versions of gemfire that's fine, it probably just needs an update to sanctionedSerializables.

**Pull request closed without merging**
