### PR TITLE
GEODE-4791: Enable gradle 4.8 for features and futureproofing

### PR DESCRIPTION
**Pull request by rhoughton-pivot**
Enable:
* Java 10 (when ready)
* remove deprecated configuration settings
* build-cache
* incremental
* parallel

Signed-off-by: Robert Houghton <rhoughton@pivotal.io>
Signed-off-by: Jens Deppe <jdeppe@pivotal.io>
Signed-off-by: Robert Houghton <rhoughton@pivotal.io>
Signed-off-by: Jens Deppe <jdeppe@pivotal.io>

Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [x] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [x] Is your initial contribution a single, squashed commit?

- [x] Does `gradlew build` run cleanly?

- [x] Have you written or updated unit tests to verify your changes?

- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by metatype** [comment]
Can you check that the `gradlew` script in the source distribution still works correctly with 4.8?

**Comment by rhoughton-pivot** [comment]
Please be more specific

**Comment by metatype** [comment]
`gradle build` creates a source distribution containing a different `gradlew` script.  Does that script still work with gradle 4.8?

**Comment by metatype** [comment]
The script in https://github.com/apache/geode/blob/develop/geode-assembly/src/src/dist/gradlew is needed so we can create create a source distribution (the official apache release) that does not contain any binaries.

**Comment by rhoughton-pivot** [comment]
Running a build using `geode-assembly/src/src/dist/gradlew assemble` worked as I would expect with the Gradle 4.8 changes.

**Comment by rhoughton-pivot** [comment]
Still facing some Tomcat invocation issues with the new Gradle version

**Pull request merged**
