### PR TITLE
Geode follows a Gitflow working model. Follow it.

### PR DESCRIPTION
**Pull request by rhoughton-pivot**
Atlassian Gitflow specifies that release branches should be merged
into both master (for a history of releases) and develop (to ensure
all bugfixes are applied). This closes that loop.

Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [ ] Is your initial contribution a single, squashed commit?

- [ ] Does `gradlew build` run cleanly?

- [ ] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, check Concourse for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by rhoughton-pivot** [comment]
@onichols-pivotal This is a merge of master to develop, which should be a fast-forward in all cases, but isn't due to this step missing in our release notes. Our confluence document is incomplete regarding the merge steps for a release. [https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)

**Comment by onichols-pivotal** [comment]
I would like to see a thumbs-up from @pivotal-jbarrett regarding the benchmarks stuff, and steps added to the release process wiki for performing this step after each future release

**Comment by onichols-pivotal** [comment]
I don't fully understand the logic for merging all changes from master to develop.  fixes of course should always be brought forward to develop too, but generally they are cherry-picked from develop to begin with.  Other release-specific changes are made on the release branch that are never intended to come back to develop, such as removing -SNAPSHOT in gradle.properties, etc.  Am I understanding that you want to change the process to bring all of these release customizations back into develop?

**Comment by rhoughton-pivot** [comment]
@upthewaterspout I pruned the files and re-pushed

**Comment by rhoughton-pivot** [comment]
@onichols-pivotal As part of the merge back to develop, the 'breaking' changes like versioning are left behind in the merge/conflict resolution stage. The point of merging releases into master, is that master is then a record of all releases. The point of merging releases (including hotfixes) back into develop, is that your project has confidence that all patches have been brought forward.

**Comment by onichols-pivotal** [comment]
> the 'breaking' changes like versioning are left behind in the merge/conflict resolution stage

this sound like a manual, non-automated process.  I am confused since earlier you said

> should be a fast-forward in all cases

**Comment by rhoughton-pivot** [comment]
@onichols-pivotal 'should be' in the general case for projects, perhaps not for our use of semver and client/server compatibility tokens.

**Comment by rhoughton-pivot** [comment]
Merging into develop, without squash or rebase. This is to preserve the history between release, master, and develop, according to the Gitflow workflow.

**Pull request merged**
