### PR TITLE
GEODE-8980: bump deps

### PR DESCRIPTION
**Pull request by onichols-pivotal**

### CODE REVIEW

**Review by dickcav — APPROVED** [review]

**Review by rhoughton-pivot — APPROVED** [review]
Brave man, updating classgraph :) LGTM

**Review by sabbey37 — APPROVED** [review]
Looks good!  I looked over the release notes for the corresponding versions of Jetty and Lettuce, but didn't see any breaking changes... so hopefully we'll be ok!

**Review by DonalEvans — CHANGES_REQUESTED** [review]
Requesting these changes be held off on briefly while I do some checks to confirm that performance isn't impacted by bumping classgraph version, as we've seen issues with that in the past.

**Review by DonalEvans — APPROVED** [review]
Thanks for your patience, everything looks ok from a performance standpoint.

**Review by jdeppe-pivotal — APPROVED** [review]

**Pull request merged**
