### PR TITLE
[GEODE-2381] make complex enums more readable

### PR DESCRIPTION
**Pull request by galen-pivotal**
* Change the style XML file to insert a line break after each constant
  of an enum.

There may be a better way to do this and allow simple enums to be all on
one line, but this looks better than what we have to me.

### CODE REVIEW

**Comment by galen-pivotal** [comment]
@jaredjstewart you know more about this than I do.
Do you know why we decided to go with the Eclipse formatter rather than [Google's java formatter](https://github.com/google/google-java-format)?

**Comment by galen-pivotal** [comment]
I don't really understand what the `48` means, but it's used elsewhere and looks something like "put everything on its own line".

**Comment by jaredjstewart** [comment]
+1, this looks much better!

**Comment by kirklund** [comment]
PS: I'm all for making more improvements to our format (including longer lines) and either making the eclipse+intellij formatters consistent (they produce different results presently) or moving to Google's java formatter if it's better and used in either IDE in some way.

**Comment by kirklund** [comment]
I squashed your 2 commits into 1 and then realized you did that on purpose. I'm going to leave it since I already pushed it.

**Comment by galen-pivotal** [comment]
@kirklund no problem, the change is what counts. 👍

**Pull request closed without merging**
