### PR TITLE
GEODE-9298: remove concourse deprecation warnings

### PR DESCRIPTION
**Pull request by rhoughton-pivot**
Merging this PR will wipe Concourse history due to pipeline and/or job
name changes.

Thank you for submitting a contribution to Apache Geode.

### CODE REVIEW

**Comment by rhoughton-pivot** [comment]
Test deployment of the `meta` pipeline here: https://concourse.apachegeode-ci.info/teams/main/pipelines/rhoughton-pivot-feature-concourse-de-meta

**Review by dickcav — APPROVED** [review]

**Comment by moleske** [comment]
If you don't want to lose history, there is an `old_name` field available which will allow you keep the history https://concourse-ci.org/jobs.html#schema.job.old_name

**Comment by rhoughton-pivot** [comment]
> If you don't want to lose history, there is an `old_name` field available which will allow you keep the history https://concourse-ci.org/jobs.html#schema.job.old_name
> 
> I used it on my current teams concourse when fixing deprecation warnings and it worked well for us. It also exists for resources

I should add that to keep folk happy.

**Comment by moleske** [comment]
@rhoughton-pivot also forgot to mention that fly has a command for rename pipeline https://concourse-ci.org/managing-pipelines.html#fly-rename-pipeline to preserve pipeline history if changing the pipeline name.  Might be harder to do with automation, but it also should be a one time thing

**Review by onichols-pivotal — APPROVED** [review]
preserving history is not important to me (Jira links to junit results and test artifacts will still work, regardless).  but if you do want to go to the trouble of adding old_name everywhere, you might consider flying it manually, rather that committing it that way (since it's really a one-time thing)

**Comment by rhoughton-pivot** [comment]
On second look, the way we have the jobs templated, we can't use any simple Jinja tricks to modify the names and keep the old ones, and the full rename-effort is not worth it for the sake of history. Any artifacts are uploaded to GCS as needed anyway.

**Review by onichols-pivotal — CHANGES_REQUESTED** [review]
please also change `_` to `-` in the three benchmarks jobs names for consistency

**Comment by rhoughton-pivot** [comment]
> please also change `_` to `-` in the three benchmarks jobs names for consistency, and update .asf.yaml as well (even though the copy on develop is not yet the source of truth, it will eventually overwrite what's on master when 1.15.0 is released)

Done. Please re-review.

**Review by onichols-pivotal — APPROVED** [review]

**Review by moleske — APPROVED** [review]
Alas, poor job history!  I knew it, Robert: pages of infinite green and red, of most excellent fancy

**Review by demery-pivotal — APPROVED** [review]
Yay! Now I can remove my keyboard's shift key!

**Pull request merged**
