### PR TITLE
GEODE-6449: Move from AWS S3 jar to buildSrc source code.

### PR DESCRIPTION
**Pull request by PurelyApplied**
Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [x] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [x] Is your initial contribution a single, squashed commit?

- [x] Does `gradlew build` run cleanly?

- [ ] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by PurelyApplied** [comment]
Mostly at @jdeppe-pivotal but anyone else who might know:

It's still not entirely clear to me what our consumption of the `gradle-dockerized-test` plugin is / how it differs from the original source.  It was my impression that it relates to some of the docker-in-docker stuff in our CI pipeline.  If that's the case, then this precheckin should properly provide confidence that these changes aren't going to cause bad leaks in our main pipeline.

If that isn't the case, however, please direct me to what tests I should execute locally to promote confidence in this diff-set.

**Comment by metatype** [comment]
What do you think about fixing this in your PR?

`ci/images/google-geode-builder/scripts/setup.sh:JDK_URL=$(curl -Ls http://jdk.java.net/11 | awk '/linux-x64/{sub(/.*href=./,"");sub(/".*/,"");if(found!=1)print;found=1}')`

**Comment by PurelyApplied** [comment]
@metatype We appear to already have that line in that file?  Did your comment get truncated and I'm missing the meaningful part of a diff or something?

**Comment by PurelyApplied** [comment]
Closing in favor of #3241

**Comment by metatype** [comment]
@PurelyApplied the line from above includes an `http` link.  We can change it to `https`.

**Pull request closed without merging**
