### PR TITLE
GEODE-7186: Move HttpService implementation into its own module

### PR DESCRIPTION
**Pull request by jdeppe-pivotal**
- For maven/gradle consumption, this component becomes an optional
  dependency.
- The CacheService.init() method now returns a boolean indicating
  whether the given service was initialized or not.
- Services are now created before cache creation resourcce events are
  emitted.

Authored-by: Jens Deppe <jdeppe@pivotal.io>

Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [ ] Is your initial contribution a single, squashed commit?

- [ ] Does `gradlew build` run cleanly?

- [ ] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, check Concourse for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by jdeppe-pivotal** [comment]
There is some code which is completely commented out in `ServerRule`. It is only used for `uiTest`s which we never run. I'm not sure what do about that but I'll try and fix  it.

**Comment by jdeppe-pivotal** [comment]
@upthewaterspout Unfortunately there is a lot of fallout when `geode-http-service` is not available on the classpath:
http://files.apachegeode-ci.info/builds/apache-develop-pr/geode-pr-4040/test-results/integrationTest/1568343482/
http://files.apachegeode-ci.info/builds/apache-develop-pr/geode-pr-4040/test-results/distributedTest/1568348689/
http://files.apachegeode-ci.info/builds/apache-develop-pr/geode-pr-4040/test-results/acceptanceTest/1568344309/

I'd propose that changes, to remove `HttpService` completely from `core`, be addressed by another PR.

**Comment by upthewaterspout** [comment]
@jdeppe-pivotal - I'm ok with removing geode-http-service from the classpath in another PR as long as the circular dependencies this PR introduces (geode-http-service -> geode-core -> geode-http-service) don't break developers IDEs.

Looks like most of these tests might be reasonable to move to geode-http-service - they are testing gfsh over http, for example.

**Comment by metatype** [comment]
> @jdeppe-pivotal - I'm ok with removing geode-http-service from the classpath in another PR as long as the circular dependencies this PR introduces (geode-http-service -> geode-core -> geode-http-service) don't break developers IDEs.

Is there a way to *avoid* creating a circular dependency entirely?  I'm not sure about the value of breaking out a new module that is still tangled up.

**Comment by jdeppe-pivotal** [comment]
@metatype Sorry I missed your comment before merging. I'm working on the next part which is exactly that: removing the circular dependency.

**Pull request merged**
