### PR TITLE
Replaced explicit null-checks by automatically generated

### PR DESCRIPTION
**Pull request by denis-zhdanov**
This *PR* applies [Traute](http://traute.oss.harmonysoft.tech/) *javac* plugin to the project. It enhances compilation process in a way to insert *null*-checks into resulting bytecode based on source code annotations.  

Let's check [LocalProcessLauncher](https://github.com/apache/geode/blob/develop/geode-core/src/main/java/org/apache/geode/internal/process/LocalProcessLauncher.java#L66):  

*Source code before*  

```java
LocalProcessLauncher(final File pidFile, final boolean force)
    throws FileAlreadyExistsException, IOException, PidUnavailableException {
  notNull(pidFile, "Invalid pidFile '" + pidFile + "' specified");
    
  this.pid = identifyPid();
  this.pidFile = pidFile;
  writePid(force);
}
```  

*Source code after*  

```java
LocalProcessLauncher(@NonNull final File pidFile, final boolean force)
    throws FileAlreadyExistsException, IOException, PidUnavailableException {
  this.pid = identifyPid();
  this.pidFile = pidFile;
  writePid(force);
}
```  

Resulting bytecode looks like if it's compiled from the source below:  

```java
LocalProcessLauncher(@NonNull final File pidFile, final boolean force)
    throws FileAlreadyExistsException, IOException, PidUnavailableException {
  if (pidFile == null) {
    throw new IllegalArgumentException("Invalid pidFile 'null' specified");
  }
  this.pid = identifyPid();
  this.pidFile = pidFile;
  writePid(force);
}
```  

*Bytecode*  

```
javap -c ./geode-core/build/classes/main/org/apache/geode/internal/process/LocalProcessLauncher.class
...
  org.apache.geode.internal.process.LocalProcessLauncher(java.io.File, boolean) throws org.apache.geode.internal.process.FileAlreadyExistsException, java.io.IOException, org.apache.geode.internal.process.PidUnavailableException;
    Code:
       0: aload_0
       1: invokespecial #2                  // Method java/lang/Object."<init>":()V
       4: aload_1
       5: ifnonnull     18
       8: new           #3                  // class java/lang/IllegalArgumentException
      11: dup
      12: ldc           #4                  // String Invalid pidFile 'null' specified
      14: invokespecial #5                  // Method java/lang/IllegalArgumentException."<init>":(Ljava/lang/String;)V
      17: athrow
       ...
```  

Benefits:  
* less boilerplate
* the code is better documented
* it's easier to add new checks (just annotate target method parameters/return values by the *NonNull* or, alternatively, [specify non-null by default](http://traute.oss.harmonysoft.tech/core/javac/#72-notnullbydefault-annotations))

### CODE REVIEW

**Comment by jdeppe-pivotal** [comment]
How does this affect the ability to debug the code? Does the plugin actually create the intermediate java files or just inject bytecode?

**Comment by denis-zhdanov** [comment]
Hey @jdeppe-pivotal,  

Generated *null*-checks are bound to the corresponding method parameter's lines, so, if you're stepping through the method call, debugger goes through them.  

*Traute* is a *javac* plugin, so, it doesn't create intermediate files but enhances the compilation in a way to insert the checks into resulting bytecode.

**Comment by metatype** [comment]
-1

I've been thinking about this PR and I don't believe it's in our best interest to merge it in.  What it would take to change my mind:

- An active community behind the project with lots of other use by well-known projects.
- A clear advantage if adopted.  Unlike kotlin, this plugin doesn't prevent NPE during coding just detects them.
- More trust about how the byte code is affected.

**Comment by denis-zhdanov** [comment]
@metatype, thanks for the feedback!
A couple of notes:
1. The project is rather young and now I'm pro-actively establish the community :)
2. An advantage is that it allows detecting problems early. Consider a situation when *null* is stored in a collection within legitimate objects for further processing. Later on you get an *NPE* but there is no clue on where it came from
3. The plugin doesn't modify bytecode, it modifies *AST* built by *javac* parser. Later on the *AST* is checked by *javac* as a part of the standard compilation. Also there is an [extensive test suite|https://github.com/denis-zhdanov/traute/tree/master/core/test/src/test/java/tech/harmonysoft/oss/traute/test/suite] for multiple use-cases

**Pull request closed without merging**
