### PR TITLE
GEODE-8249: change more string commands to have CommandFunction support

### PR DESCRIPTION
**Pull request by dschneider-pivotal**
Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [ ] Is your initial contribution a single, squashed commit?

- [ ] Does `gradlew build` run cleanly?

- [ ] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, check Concourse for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by jdeppe-pivotal** [comment]
I was trying some string OPs and saw this with `BITOP NOT`:
```
java.lang.ClassCastException: org.apache.geode.internal.cache.LocalDataSet cannot be cast to org.apache.geode.internal.cache.InternalRegion
        at Remote Member '192.168.1.5(server2:78554)<v2>:41002' in org.apache.geode.internal.cache.execute.InternalFunctionExecutionServiceImpl.isClientRegion(InternalFunctionExecutionSe
rviceImpl.java:400)
        at Remote Member '192.168.1.5(server2:78554)<v2>:41002' in org.apache.geode.internal.cache.execute.InternalFunctionExecutionServiceImpl.onRegion(InternalFunctionExecutionServiceI
mpl.java:146)
        at Remote Member '192.168.1.5(server2:78554)<v2>:41002' in org.apache.geode.cache.execute.FunctionService.onRegion(FunctionService.java:76)
        at Remote Member '192.168.1.5(server2:78554)<v2>:41002' in org.apache.geode.redis.internal.executor.CommandFunction.execute(CommandFunction.java:52)
        at Remote Member '192.168.1.5(server2:78554)<v2>:41002' in org.apache.geode.redis.internal.executor.string.RedisStringCommandsFunctionExecutor.get(RedisStringCommandsFunctionExec
utor.java:57)
        at Remote Member '192.168.1.5(server2:78554)<v2>:41002' in org.apache.geode.redis.internal.data.RedisStringInRegion.bitop(RedisStringInRegion.java:177)
        at Remote Member '192.168.1.5(server2:78554)<v2>:41002' in org.apache.geode.redis.internal.executor.CommandFunction.lambda$compute$19(CommandFunction.java:177)
        at Remote Member '192.168.1.5(server2:78554)<v2>:41002' in org.apache.geode.redis.internal.executor.CommandFunction.compute(CommandFunction.java:335)
        at Remote Member '192.168.1.5(server2:78554)<v2>:41002' in org.apache.geode.redis.internal.executor.SingleResultRedisFunction.lambda$execute$0(SingleResultRedisFunction.java:51)
        at Remote Member '192.168.1.5(server2:78554)<v2>:41002' in org.apache.geode.internal.cache.PartitionedRegion.computeWithPrimaryLocked(PartitionedRegion.java:631)
        at Remote Member '192.168.1.5(server2:78554)<v2>:41002' in org.apache.geode.redis.internal.executor.SingleResultRedisFunction.computeWithPrimaryLocked(SingleResultRedisFunction.j
ava:71)
        at Remote Member '192.168.1.5(server2:78554)<v2>:41002' in org.apache.geode.redis.internal.executor.SingleResultRedisFunction.execute(SingleResultRedisFunction.java:55)
        at Remote Member '192.168.1.5(server2:78554)<v2>:41002' in org.apache.geode.internal.cache.PartitionedRegionDataStore.executeOnDataStore(PartitionedRegionDataStore.java:2996)
        at Remote Member '192.168.1.5(server2:78554)<v2>:41002' in org.apache.geode.internal.cache.partitioned.PartitionedRegionFunctionStreamingMessage.operateOnPartitionedRegion(PartitionedRegionFunctionStreamingMessage.java:101)
        at Remote Member '192.168.1.5(server2:78554)<v2>:41002' in org.apache.geode.internal.cache.partitioned.PartitionMessage.process(PartitionMessage.java:333)
        at Remote Member '192.168.1.5(server2:78554)<v2>:41002' in org.apache.geode.distributed.internal.DistributionMessage.scheduleAction(DistributionMessage.java:376)
        at Remote Member '192.168.1.5(server2:78554)<v2>:41002' in org.apache.geode.distributed.internal.DistributionMessage$1.run(DistributionMessage.java:441)
        at Remote Member '192.168.1.5(server2:78554)<v2>:41002' in java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at Remote Member '192.168.1.5(server2:78554)<v2>:41002' in java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at Remote Member '192.168.1.5(server2:78554)<v2>:41002' in org.apache.geode.distributed.internal.ClusterOperationExecutors.runUntilShutdown(ClusterOperationExecutors.java:442)
        at Remote Member '192.168.1.5(server2:78554)<v2>:41002' in org.apache.geode.distributed.internal.ClusterOperationExecutors.doFunctionExecutionThread(ClusterOperationExecutors.java:377)
```

**Comment by jdeppe-pivotal** [comment]
`INCRBYFLOAT` gives the following error and the `redis-cli` exits. It works fine in native redis:
```
127.0.0.1:6379> incrbyfloat foo 1.1
Error: Protocol error, got "4" as reply type byte
```
However, when I reconnect `foo` appears to have been incremented correctly.

**Comment by dschneider-pivotal** [comment]
I fixed the issues Jens found and added integration tests for all these string commands

**Comment by dschneider-pivotal** [comment]
the upgrade test failure is a known issue unrelated to this PR

**Pull request merged**
