### PR TITLE
GEODE-6716 Multiple ClassLoaders for a single deployed jar

### PR DESCRIPTION
**Pull request by mkevo**
Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [x] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [x] Is your initial contribution a single, squashed commit?

- [x] Does `gradlew build` run cleanly?

- [x] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, check Concourse for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by jdeppe-pivotal** [comment]
@jhuynh1 Is this related to the work you're doing with class loading?

**Comment by jhuynh1** [comment]
@jdeppe-pivotal This is related to the changes I've been looking at.  This PR will solve the case where the same jar is redeployed, but it won't handle the case where an unrelated jar is deployed.  For example if we deploy jar A and put some keys into the region that used classes in jar A, if we then deploy jar B, we would still create a new class loader containing both A and B but the same problem of instanceof checks would exist.

My current WIP to chain classloaders is at:  
https://github.com/apache/geode/pull/3537
I am not sure if it will be a valid solution until I test it out a bit more but precheckin has passed.

**Comment by mkevo** [comment]
I tested with [#3537](https://github.com/apache/geode/pull/3537) and this will be fixed with that changes. After merging PR [#3537](https://github.com/apache/geode/pull/3537) to develop branch I will close this PR and reference the ticket to [GEODE-6822](https://issues.apache.org/jira/browse/GEODE-6822) as duplicated.

**Comment by mkevo** [comment]
[#3537](https://github.com/apache/geode/pull/3537) is merged to develop branch, I tested it and it works. So I will close this PR as it is not needed.

**Pull request closed without merging**
