### PR TITLE
GEODE-6399: Manage dependency versions via java-platform

### PR DESCRIPTION
**Pull request by PurelyApplied**
Depends on PR #3189 

Please review in particular the set of published artifacts whose version is constrained by the new BOM.  Are there any artifacts that should be exempt from this list?

----

* All applicable projects should opt into dependency version management
via bom consumption, i.e.,
compile(platform(project(':boms:geode-all-bom')))

* Those configurations that do not extend compile, such as compileOnly
or those provided by other plugins, will also require a dependency on
the platform's BOM

* The BOM itself is now configured via the buildSrc
DependencyConstraints.groovy.  This replaces
geode-dependency-management.gradle.

* Those lingering "property" versions are now accessible via
DependencyConstraints.get() rather than project properties.

* Published POMs now correctly consume the Geode BOM, rather than
reproducing the same dependencyManagement block across all POMs.

* publish.gradle now sets the project property constrainVersionInBom,
indicating that the published artifact should be constrained to the same
version in the geode-all-bom as the BOM itself.

Co-authored-by: Patrick Rhomberg <prhomberg@pivotal.io>
Co-authored-by: Robert Houghton <rhoughton@pivotal.io>

------

Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [ ] Is your initial contribution a single, squashed commit?

- [x] Does `gradlew build` run cleanly?

- [ ] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by rhoughton-pivot** [comment]
`geode-assembly` is publishing a TGZ, but the associated POM contains a dependency on geode-all-bom? Shouldn't the TGZ contain geode-all-bom.pom, instead of depending on it? This is confusing.

**Comment by PurelyApplied** [comment]
Good catch.

**Comment by PurelyApplied** [comment]
UnitTest failures currently persistent on `develop`.  IntegrationTest resource NPEs require investigation.

**Comment by PurelyApplied** [comment]
It looks like the NPE was from the `geode-core` serializables class requiring the `geode-core-sanctioned-serializables` to be present in its resource path.  It had previously happily gotten the resource from the `geode-core.jar`, but with the constraints in place, was no longer happy to do so.

That seems like convoluted logic in and of itself.  And as these tests are a constant source of pain, we should look to shifting their intent into something that is not so brittle when directories or files shift.  They might make more sense as gradle commands than as integration tests, since gradle will more easily blow away lingering artifacts that are present in, say, a `lib` or `resource` directory.

**Comment by PurelyApplied** [comment]
Failures appear to be (similar to) GEODE-6436 and (exactly) GEODE-6437 in test `RebalanceOperationDUnitTest` and `ClusterConfigLocatorRestartDUnitTest` respectively.

**Comment by PurelyApplied** [comment]
As of `99c6bdb`, failures present in this PR were failures in the `develop` pipeline.

**Pull request merged**
