### PR TITLE
GEODE-9568: UG build script keep doc after generating it

### PR DESCRIPTION
**Pull request by alb3rtobr**
UG build script allows to preview the user guide but the generated files are deleted as they are created inside a container.
This PR causes the generated files are not deleted after the script ends.

### CODE REVIEW

**Comment by davebarnes97** [comment]
Thanks for your contribution @alb3rtobr. I'm reviewing as my schedule permits, may take another day. Thanks for your patience.

**Comment by davebarnes97** [comment]
@alb3rtobr I followed the README.md instructions, which were unaltered by this PR. The script executed to completion, but with a Bundler warning (occurred twice) and cryptic script output (the displayed paths appear to be self-referential symlinks). See transcript below. I was able to preview the results, as before, but was not sure where to find the user guide. Could the script simply place its result in geode-book/final_app, just as a manual run of the tools would do?
```
29:geode-book$ cd ../dev-tools/docker/docs
30:docs$ ./preview-user-guide.sh
Sending build context to Docker daemon  14.34kB
Step 1/9 : FROM ruby:2.5
 ---> 13fd310aa3ad
Step 2/9 : LABEL Vendor="Apache Geode"
 ---> Using cache
 ---> cb656eb66448
Step 3/9 : LABEL version=unstable
 ---> Using cache
 ---> 157447c79832
Step 4/9 : LABEL maintainer=dev@geode.apache.org
 ---> Using cache
 ---> 58658cac5334
Step 5/9 : RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash - ;     apt-get install -y nodejs
 ---> Using cache
 ---> cbacd542759d
Step 6/9 : RUN gem install bundler:1.17.3     rake multi_json:1.13.1     elasticsearch:2.0.2     multipart-post:2.0.0     faraday:0.15.4     libv8:3.16.14.15     mini_portile2:2.5.0     racc:1.5.2     nokogiri:1.11.2     mimemagic:0.3.9     puma:4.3.8     rack:2.1.4     smtpapi:0.1.0     sendgrid-ruby:1.1.6     therubyracer:0.12.2
 ---> Using cache
 ---> 4b1c8551e511
Step 7/9 : COPY Gemfile Gemfile
 ---> Using cache
 ---> 52d189ad376f
Step 8/9 : COPY Gemfile.lock Gemfile.lock
 ---> Using cache
 ---> 5f239f86c681
Step 9/9 : RUN bundle install
 ---> Using cache
 ---> 455b233b66b7
Successfully built 455b233b66b7
Successfully tagged geodedocs/temp:1.0
./preview-user-guide.sh: line 36: UID: readonly variable
`/` is not writable.
Bundler will use `/tmp/bundler/home/unknown' as your home directory temporarily.
/usr/local/bundle/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/resource.rb:88: warning: constant ::Fixnum is deprecated
Gathering geode-docs
  copying /geode-docs
/usr/local/bundle/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/resource.rb:88: warning: constant ::Fixnum is deprecated


Checking for broken links...

No broken links!
Bookbinder bound your book into /geode-book/final_app
`/` is not writable.
Bundler will use `/tmp/bundler/home/unknown' as your home directory temporarily.
Puma starting in single mode...
* Version 4.3.8 (ruby 2.5.9-p229), codename: Mysterious Traveller
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:9292
Use Ctrl-C to stop
172.17.0.1 - - [29/Sep/2021:17:12:08 +0000] "GET /docs/guide/115/about_geode.html HTTP/1.1" 200 - 0.0495
172.17.0.1 - - [29/Sep/2021:17:12:08 +0000] "GET /stylesheets/all.css HTTP/1.1" 200 - 0.0263
172.17.0.1 - - [29/Sep/2021:17:12:08 +0000] "GET /javascripts/all.js HTTP/1.1" 200 - 0.0313
172.17.0.1 - - [29/Sep/2021:17:12:08 +0000] "GET /stylesheets/print.css HTTP/1.1" 200 - 0.0256
172.17.0.1 - - [29/Sep/2021:17:12:08 +0000] "GET /images/Apache_Geode_logo_symbol.png HTTP/1.1" 200 - 0.0325
172.17.0.1 - - [29/Sep/2021:17:12:08 +0000] "GET /fonts/font-awesome/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 200 - 0.0584
172.17.0.1 - - [29/Sep/2021:17:12:15 +0000] "GET /docs/guide/115/tools_modules/book_intro.html HTTP/1.1" 200 - 0.0359
172.17.0.1 - - [29/Sep/2021:17:12:19 +0000] "GET /docs/guide/115/reference/book_intro.html HTTP/1.1" 200 - 0.0343
^C- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2021-09-29 17:12:55 +0000 ===
- Goodbye!
115
/Users/dbarnes/Repo/geode/dev-tools/docker/docs/../../../geode-book/output/master_middleman/source/docs/guide/115
/Users/dbarnes/Repo/geode/dev-tools/docker/docs/../../../geode-book/output/preprocessing/sections/docs/guide/115
$ ls -l /Users/dbarnes/Repo/geode/dev-tools/docker/docs/../../../geode-book/output/master_middleman/source/docs/guide/115
lrwxr-xr-x  1 dbarnes  staff  112 Sep 29 10:12 /Users/dbarnes/Repo/geode/dev-tools/docker/docs/../../../geode-book/output/master_middleman/source/docs/guide/115@ -> /Users/dbarnes/Repo/geode/dev-tools/docker/docs/../../../geode-book/output/preprocessing/sections/docs/guide/115
```

**Comment by alb3rtobr** [comment]
I left some printouts in the scripts by mistake, sorry for the confusion, Im going to remove them.

The user guide should be at the same place that bookbinder creates it, I have not changed that:

```
$ ls -las ../../../geode-book/final_app/public/docs/guide/115/
total 440
  4 drwxr-xr-x 14 alb3rtobr alb3rtobr   4096 sep 29 22:38 .
  4 drwxr-xr-x  3 alb3rtobr alb3rtobr   4096 sep 29 22:38 ..
188 -rw-r--r--  1 alb3rtobr alb3rtobr 189027 sep 29 22:38 about_geode.html
  4 drwxr-xr-x  7 alb3rtobr alb3rtobr   4096 sep 29 22:38 basic_config
  4 drwxr-xr-x  4 alb3rtobr alb3rtobr   4096 sep 29 22:38 configuring
  8 -rw-r--r--  1 alb3rtobr alb3rtobr   5591 sep 29 22:38 CONTRIBUTE
  4 drwxr-xr-x 19 alb3rtobr alb3rtobr   4096 sep 29 22:38 developing
  4 drwxr-xr-x  5 alb3rtobr alb3rtobr   4096 sep 29 22:38 getting_started
  4 drwxr-xr-x  2 alb3rtobr alb3rtobr   4096 sep 29 22:38 images
  4 drwxr-xr-x  2 alb3rtobr alb3rtobr   4096 sep 29 22:38 images_svg
  4 drwxr-xr-x 12 alb3rtobr alb3rtobr   4096 sep 29 22:38 managing
188 -rw-r--r--  1 alb3rtobr alb3rtobr 189484 sep 29 22:38 prereq_and_install.html
  4 drwxr-xr-x  4 alb3rtobr alb3rtobr   4096 sep 29 22:38 reference
  4 drwxr-xr-x  2 alb3rtobr alb3rtobr   4096 sep 29 22:38 rest_apps
  4 drwxr-xr-x  7 alb3rtobr alb3rtobr   4096 sep 29 22:38 tools_modules
  4 drwxr-xr-x  6 alb3rtobr alb3rtobr   4096 sep 29 22:38 topologies_and_comm
  4 drwxr-xr-x  2 alb3rtobr alb3rtobr   4096 sep 29 22:38 use_cases

```

Are you missing anything else?

**Comment by davebarnes97** [comment]
Looks much better now. The results are good. I still received these warnings - can they be cleaned up, or do we have to live with them, as we do with the 'Fixnum' message that always appears :
```
./preview-user-guide.sh: line 36: UID: readonly variable
```
and
```
`/` is not writable.
Bundler will use `/tmp/bundler/home/unknown' as your home directory temporarily.
```

**Comment by alb3rtobr** [comment]
Thanks for pointing that out. I have fixed the first error, but the other one it seems its related with bookbinder, but it seems we can live with it. In my case, I see:

```
`/home/alb3rtobr` is not writable.
Bundler will use `/tmp/bundler/home/unknown' as your home directory temporarily.
```

**Review by davebarnes97 — APPROVED** [review]
Thank you for addressing the read-only variable error. I agree that we can live with the remaining warnings.
It's great that the script now leaves a compiled user guide for the user to keep, if wanted.

**Pull request merged**
