### PR TITLE
do not review

### PR DESCRIPTION
**Pull request by dschneider-pivotal**
Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [ ] Is your initial contribution a single, squashed commit?

- [ ] Does `gradlew build` run cleanly?

- [ ] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, check Concourse for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by dschneider-pivotal** [comment]
The following unit test failed. It does not reproduce when run from the IDE:
 > Task :geode-concurrency-test:test

org.apache.geode.test.concurrency.ConcurrentTestRunnerTest$FailingTest > test FAILED
    java.util.concurrent.ExecutionException: java.lang.AssertionError: 
    Expecting actual not to be null
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.apache.geode.test.concurrency.loop.LoopRunner$DelegatingExecutor.execute(LoopRunner.java:101)
        at org.apache.geode.test.concurrency.ConcurrentTestRunnerTest$BaseTest.test(ConcurrentTestRunnerTest.java:59)
        at org.apache.geode.test.concurrency.ConcurrentTestRunnerTest$FailingTest.test(ConcurrentTestRunnerTest.java:71)

        Caused by:
        java.lang.AssertionError: 
        Expecting actual not to be null

**Comment by dschneider-pivotal** [comment]
The following test is failing:
org.apache.geode.internal.cache.tier.sockets.ConnectionProxyJUnitTest > testDeadServerMonitorPingNature1 FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined in public void org.apache.geode.internal.cache.tier.sockets.ConnectionProxyJUnitTest.testDeadServerMonitorPingNature1() null within 300 seconds.
        at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:145)
        at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:122)
        at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:32)
        at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:902)
        at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:723)
        at org.apache.geode.internal.cache.tier.sockets.ConnectionProxyJUnitTest.testDeadServerMonitorPingNature1(ConnectionProxyJUnitTest.java:255)

It looks to me like what this test depends on is that prefill will create a connection. But, at least the initial prefill does not happen because it thinks we are already at the min of one because at the same time the prefill thread checked to see if count was at min, another test thread tried to connect. It failed but while it is trying to connect it sets count to 1. Still debugging to see why prefill did not get rescheduled later

**Comment by pivotal-jbarrett** [comment]
> org.apache.geode.test.concurrency.ConcurrentTestRunnerTest
This may be a concurrency difference between hosts. Since this tests is trying to expose a know concurrency issue to test that the concurrency test framework can find such issues its possible that load or configuration or whatever prevents the test from failing as expected.

**Comment by balesh2** [comment]
Closing as duplicate

**Pull request closed without merging**
