### PR TITLE
GEODE-10055: fix AbstractLauncher to print info and debug with stdout

### PR DESCRIPTION
**Pull request by mkevo**
### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [X] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [X] Is your initial contribution a single, squashed commit?

- [X] Does `gradlew build` run cleanly?

- [ ] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### CODE REVIEW

**Review by onichols-pivotal — COMMENTED** [review]
_comment deleted_

**Comment by mkevo** [comment]
@echobravopapa, @Bill, @kirklund, @kamilla1201, can you please add your review on this?

**Review by kirklund — COMMENTED** [review]
This change should be ok, but I think it needs some sort of test.

**Comment by mkevo** [comment]
> This change should be ok, but I think it needs some sort of test.

Hi @kirklund ,
The PR only changes the log level of some messages, so I don't think that we need test as we don't change any functionality.
BR,
Mario

**Comment by mkevo** [comment]
@echobravopapa, @kamilla1201, @Bill, can you please review this small change?

**Comment by mkevo** [comment]
@echobravopapa, @kamilla1201, @Bill, can you please review this change?

**Review by kamilla1201 — APPROVED** [review]

**Review by pivotal-jbarrett — DISMISSED** [review]
I am quite certain this is intentional. Perhaps it is worth a conversation on dev@geode to see if we want to change this.

**Comment by mkevo** [comment]
> I am quite certain this is intentional. Perhaps it is worth a conversation on dev@geode to see if we want to change this.

Hi @pivotal-jbarrett, why do you think that this is intentional?
I saw that it prints messages like _'Getting Locator status using working directory'_. Not sure that this should be printed as an error, maybe I'm wrong, but need some clarification of your thoughts. Thanks!

**Comment by pivotal-jbarrett** [comment]
It is common in console programming to output "verbose" output to stderr and "normal" output to stdout. Verbose output being log like stuff and normal output being results of the execution. The rational for this is to be able to split the output like this.
```shell
$ hello-world 2>/tmp/hello-world.log
Hello World

$ cat /tmp/hello-world.log
06-14-2022 10:11:12 PDT - INFO - hello-world starting.
06-14-2022 10:11:12 PDT - WARN - something doesn't feel right today.
06-14-2022 10:11:12 PDT - INFO - hello-world stopping.
```

**Review by kirklund — APPROVED** [review]

**Pull request merged**
