### PR TITLE
GEODE-2309: Replace Pivotal Copyright and add Apache License notice.

### PR DESCRIPTION
**Pull request by pivotal-jbarrett**
Can I please get quick review of the copyright and license changes.

### CODE REVIEW

**Comment by upthewaterspout** [comment]
Looks good so far, but there are still a lot of files missing apache headers. I don't know how easy it will be to integrate [apache rat](https://creadur.apache.org/rat/) into the cmake build, but for now you can run it from the command line to get a list of files that are missing licenses:

java -jar /path/to/apache-rat-0.12.jar  .

I see a few java files, shell scripts, text files, and a lot of xml files without apache headers.
[missing_licences.txt](https://github.com/apache/geode/files/712483/missing_licences.txt)

**Comment by pivotal-jbarrett** [comment]
In this push I am only trying to tackle the changing of licenses and adding to the obvious sources. We will integrated something a little more like rat (see email GEODE-2312 about rat issues).

**Comment by metatype** [comment]
LGTM, these changes typically take multiple iterations to get right.

**Comment by scmbuildguy** [comment]
+1 for this round

**Pull request closed without merging**
