### PR TITLE
Align logo, edit PR template

### PR DESCRIPTION
**Pull request by fredster33**
Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [ ] Is your initial contribution a single, squashed commit?

- [X] Does `gradlew build` run cleanly?

- [X] Have you written or updated unit tests to verify your changes?

- [X] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, check Concourse for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by kohlmu-pivotal** [comment]
@pivotal-amurmann @upthewaterspout could you possibly have a look at this.

**Review by upthewaterspout — CHANGES_REQUESTED** [review]
Hi,

Thanks for the PR. Can you clarify why you felt like we should remove those sections of the PR template?

**Comment by fredster33** [comment]
Hi @upthewaterspout , and thanks for the question. Sorry, missed this in my inbox. I commented out, not removed, these sections, so that the guidance appears in the PR when contributors write the content for the PR description, but that the content doesn't appear when displaying after the PR has published. The content is still available when re-editing the PR.

**Review by rhoughton-pivot — APPROVED** [review]

**Comment by onichols-pivotal** [comment]
@upthewaterspout have your concerns now been addressed?  If so please change your -1 to a +1 and merge this, since submitter is not a committer.  If not, please restate what still needs to be changed.

**Review by upthewaterspout — APPROVED** [review]
> I commented out, not removed, these sections, so that the guidance appears in the PR when contributors write the content for the PR description, but that the content doesn't appear when displaying after the PR has published

Ahh, I see. Ok, in that case it looks good.

**Pull request merged**
