### PR TITLE
GEODE-1074 Create geode-gfsh project.

### PR DESCRIPTION
**Pull request by rhoughton-pivot**
Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [X] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [X] Is your initial contribution a single, squashed commit?

- [X] Does `gradlew build` run cleanly?

- [X] Have you written or updated unit tests to verify your changes?

- [X] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, check Concourse for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by pivotal-jbarrett** [comment]
It does look like it removes the manifest jar. We probably need to keep that around until the next major as "api".

**Comment by rhoughton-pivot** [comment]
@upthewaterspout Currently this is a fat-jar of all dependencies. The up-side is that it would give a single artifact for download that would allow CLI interface with a running cluster. I was literally testing with `java -jar geode-gfsh.jar` and getting good results

**Comment by rhoughton-pivot** [comment]
@pivotal-jbarrett Note, this is only a draft so far

**Comment by jinmeiliao** [comment]
if we do decide to do this. Core needs to depend on this gfsh.jar. Or we can move all the commands  to a module, create commands.jar, and have geode-core and geode-gfsh both depend on that.

**Comment by jdeppe-pivotal** [comment]
You'll probably discover this when looking at the test failures, but the default build doesn't build `lib/geode-gfsh-x.y.z.jar`

**Comment by jdeppe-pivotal** [comment]
@jinmeiliao I'm not sure that `geode-core` needs to depend on this but it is a good idea to pull all the gfsh commands into their own module.

**Comment by rhoughton-pivot** [comment]
@jdeppe-pivotal I'll modify the build ordering to make sure that `:geode-gfsh:bootJar` is on the default `build` list.

**Comment by jdeppe-pivotal** [comment]
Zip files are nice because the directory info is appended at the **end** of the file which allows for interesting things like prepending an `exe` to the zip. Although this current solution gets to the point of allowing a user to simply do `java -jar geode-gfsh.jar` we could take it one step further and prepend a small exe which essentially does what the `gfsh` script  does now. So it would truly be a single executable. Yes, that would mean separate binaries for each OS.

For inspiration: https://github.com/GeertJohan/go.rice

**Comment by jdeppe-pivotal** [comment]
In case anyone keeps working on this, I did a bit more work to allow launching locators and servers and running embedded webapps: https://github.com/jdeppe-pivotal/geode/commit/e56aa2c2aeaeda4bbe1e78d69004fb549590020e

**Comment by jmelchio** [comment]
@rhoughton-pivot given that we now have a `geode-gfsh` module should this be closed?

**Comment by metatype** [comment]
Closing this out in favor of doing an RFC.  We can still refer to the ideas proposed in this PR.

**Pull request closed without merging**
