### PR TITLE
GEODE-3151: Internal Region Registration in JMX as per config parameter

### PR DESCRIPTION
**Pull request by dineshpune2006**
Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X ] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [X ] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [ X] Is your initial contribution a single, squashed commit?

- [X ] Does `gradlew build` run cleanly?

- [ X] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by PurelyApplied** [comment]
If you are using IntelliJ as your IDE, please remember to update your style file to that located in `geode/etc/intellij-java-modified-google-style.xml` to be consistent with Geode's established style guide.  This file was updated June 13 with commit `a561bd12` to be consistent with documented expectations.

After having done so, please optimize the imports to the correct order and to eliminate the use of the wildcard imports.

**Comment by dineshpune2006** [comment]
i have added  etc/eclipseFormatterProfile.xml in eclipse profile & did the code style set.

**Comment by kirklund** [comment]
I think this sort of change should be proposed and discussed on the dev list. This is effectively adding new User APIs and that requires more discussion.

**Comment by jaredjstewart** [comment]
Hi Dinesh,

Sorry to be so slow in responding to your PR.  Since the changes you are proposing in GEODE-3151 involve changing a public-facing API (in DistributionConfig, I think it first needs to be discussed on dev@geode.apache.org before we could pull this in.  Would you mind sending an email to that list with your proposal and the use-case you have in mind?

Thank you,
Jared

**Comment by dineshpune2006** [comment]
no need.

**Pull request closed without merging**
