### PR TITLE
Feature/geode 2103 : Adding --http-service-port and --http-service-bind-address option in start locator command

### PR DESCRIPTION
**Pull request by deepakddixit**
Added --http-service-port and --http-service-bind-address options in start locator command.

### CODE REVIEW

**Comment by metatype** [comment]
IIRC, there's an integration test that should be updated with the new options.  Take a look at `geode-core/src/test/resources/org/apache/geode/management/internal/cli/commands/golden-help-offline.properties`.

**Comment by deepakddixit** [comment]
@metatype I have updated the golden-help-offline.properties. The integration test HelpCommandsIntegrationTest is generic one checking the help <command> and confirms the contents from golden-help-offline.properties. It is passing with changes made in golden-help-offline.properties

**Comment by metatype** [comment]
@jinmeiliao any thoughts on this change?

**Comment by jinmeiliao** [comment]
the changes look good to me. Running all tests now. Will pull this in if no test failures.

**Pull request closed without merging**
