### PR TITLE
GEODE-2908: Adding the new tag as per swagger notification.

### PR DESCRIPTION
**Pull request by prasi-in**
Adding the new tags in the swagger annotations which will displayed in the Swagger UI

### CODE REVIEW

**Comment by davinash** [comment]
@prasi-in Can you  please fix the imports.

**Comment by prasi-in** [comment]
Fixed the imports.

**Comment by metatype** [comment]
@jaredjstewart any thoughts on this change?  If it's good I'd like to merge it since we need it for 1.2.0.

**Comment by jaredjstewart** [comment]
Looks good to me.  I'll merge it in shortly and cherry pick onto the release branch.

**Comment by jaredjstewart** [comment]
Merged as `ac404ad`.  Thank you for your contribution!

**Comment by jaredjstewart** [comment]
This PR has already been merged in, but feel free to open a new ticket for that.  We unfortunately still have a lot of other "gemfire" references scattered around.

**Comment by davebarnes97** [comment]
Will add my comment to GEODE-3035 Rest: Swagger UI has lot of references to GemFire, instead they should be changed to geode

**Comment by jdeppe-pivotal** [comment]
Already merged

**Pull request closed without merging**
