### PR TITLE
GEODE-2370: First pass at a CONTRIBUTING document.

### PR DESCRIPTION
**Pull request by echobravopapa**
Just a start with into covering c++ formatting that is not in the BUILDING.md
This can be expanded as the community desires...

### CODE REVIEW

**Comment by davinash** [comment]
IMO we also should add command on how to run integration run.
I could run integration tests using following command.
`cmake --build . --target run-integration-tests`

**Comment by echobravopapa** [comment]
@davinash sounds like a good idea I'll have updated document today

**Comment by davinash** [comment]
LGTM
one question since I am new to CMAKE, how can we run single test ? And should we include instructions for a the same

**Comment by pivotal-jbarrett** [comment]
We should include links to CTest documents.

To run singles or subsets of tests you need to use ctest directly. 

ctest -R <regex>

**Comment by davinash** [comment]
+1

**Comment by echobravopapa** [comment]
The latest doc in PR has instructions on running a single ctest...

**Comment by pivotal-jbarrett** [comment]
Merged, please close.

**Pull request closed without merging**
