### PR TITLE
Migrate to JUnit 5 framework.

### PR DESCRIPTION
**Pull request by pivotal-jbarrett**
Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [ ] Is your initial contribution a single, squashed commit?

- [ ] Does `gradlew build` run cleanly?

- [ ] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, check Concourse for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by pivotal-jbarrett** [comment]
@dhemery can you take a quick look at the results. I fear they might be false positives. I would like two eyes on them.

**Comment by pivotal-jbarrett** [comment]
As I suspected, something is up. Far fewer tests run in distributed tests.
PR: https://concourse.apachegeode-ci.info/builds/171472
Main: https://concourse.apachegeode-ci.info/teams/main/pipelines/apache-develop-main/jobs/DistributedTestOpenJDK11/builds/331

**Comment by demery-pivotal** [comment]
In a cursory scan (about 1% of the 2000+ tests), I noticed:
- Every test that was missing from the JUnit 5 test run was in geode-core distributedTest.
- Every geode-core distributedTest was missing from the JUnit 5 test run.

**Comment by pivotal-jbarrett** [comment]
> In a cursory scan (about 1% of the 2000+ tests), I noticed:
> 
> * Every test that was missing from the JUnit 5 test run was in geode-core distributedTest.
> * Every geode-core distributedTest was missing from the JUnit 5 test run.

So you are saying there is a problem... Any ideas? Did you notice if other non geode-core distributedTests ran?

**Comment by demery-pivotal** [comment]
Definitely a problem. Lacking ideas, I explored a little further.

I checked the distributed tests in several modules, and each had tests that DID run in your PR:

- geode-connectors
- geode-cq
- geode-dunit
- geode-gfsh
- geode-wan
- geode-web
- geode-web-management

I did not do a full search to see if any distributed tests from those modules are missing. But each distributedTest class that I checked from each of those modules was run in your PR.

I searched the names of the test classes that ran in your PR and found:

- 55 class names with DistributedTest
- 308 class names with DUnitTest
- 73 additional class names with DUnit

So it appears that there are lots of distributedTests running.

I was suspicious of this in geode-core's build.gradle file (though I couldn't see how it would affect test class selection):

    distributedTest {
        // Some tests have inner tests that should be ignored
        exclude "**/*\$*.class"
    }

But geode-dunit has the same exclusion in its distributedTest dependencies, and its tests ran in your PR.

Several other modules (geode-logging, geode-membership, and geode-serialization) declare the same exclusion in the distributedTest dependencies, though they don't seem to actually have a distributedTest directory.

**Comment by pivotal-jbarrett** [comment]
So strange. I will try to take a look at this again to see what's up. There must be something uniquely interesting about geode-core that is pissing off the docker plugin.

**Comment by onichols-pivotal** [comment]
last activity was some while ago, is this PR still active?

**Pull request closed without merging**
