### PR TITLE
[DO NOT MERGE] Revert "GEODE-9778: Bump netty from 4.1.67.Final to 4.1.70.Final (#7075)

### PR DESCRIPTION
**Pull request by jdeppe-pivotal**
This reverts commit 7f4bf62a08b24aca81fe05349cdc72d919a6cab7.

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [ ] Is your initial contribution a single, squashed commit?

- [ ] Does `gradlew build` run cleanly?

- [ ] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### CODE REVIEW

**Comment by jdeppe-pivotal** [comment]
This is just in case the original commit doesn't work and I need to revert again. If the pipeline goes green for https://github.com/apache/geode/pull/7075 I'll close this PR.

**Review by onichols-pivotal — APPROVED** [review]
hope you don't need this, but approving just in case

**Review by dickcav — APPROVED** [review]
ditto

**Comment by jdeppe-pivotal** [comment]
The fix worked - there is no need to revert so this PR can be closed.

**Pull request closed without merging**
