### PR TITLE
GEODE-234: Removed deprecated MirrorType class and its usage is replaced by appropriate DataPolicy.REPLICATE or DataPolicy.NORMAL

### PR DESCRIPTION
**Pull request by davinash**
- Did not find cache-9.0.xsd in source. So I am assuming this file will get added later.
- geode-docs still has reference to mirror-type.
- ConsoleDistributionManagerDUnitTest#testApplications is failing ( FlakyTest )
- ClusterConfigurationServiceEndToEndDUnitTest#testStartServerAndExecuteCommands is failing ( FlakyTest)

### CODE REVIEW

**Comment by dschneider-pivotal** [comment]
The xsd you are looking for is: geode-core/build/resources/main/META-INF/schemas/geode.apache.org/schema/cache/cache-1.0.xsd

However you should not modify this one since it has already been released.
The next geode release will be 1.2 so you would want to create a new cache-1.2.xsd and remove mirror-type from it. Introducing a new xsd involves a bunch of busy work.
You need to add org.apache.geode.internal.cache.xmlcache.CacheXml.VERSION_1_2,
update CacheXml.VERSION_LATEST,
add CacheXml.SCHEMA_1_2_LOCATION,
add CacheXmlVersion.GEODE_1_2,
add CacheXmlGeode12DUnitTest that extends CacheXmlGeode10DUnitTest.
I'm not sure what should be done about these dunit tests. They test the old xsd/dtds which still do support mirror-type. If we remove support for the mirror-type attribute from the xml parser code then all these old dtds and xsds will no longer support  mirror-type in their xml even though the old dtd/xsd says it does. I think all the old dtds we still support also have data-policy so even with that old dtd you could convert the mirror-type attribute to data-policy in you existing xml.

**Comment by davinash** [comment]
Thanks @dschneider-pivotal for the review.
Do you want CacheXML and dtd  changes part of this PR.

**Comment by dschneider-pivotal** [comment]
Yes. I think it is just xsd (not dtd) changes and the java changes needed when adding a new xsd.

**Comment by galen-pivotal** [comment]
Closing due to age and inactivity.

**Pull request closed without merging**
