### PR TITLE
GEODE-6979: Clean files in ExportLogsStatsDistributedTestBase

### PR DESCRIPTION
**Pull request by alb3rtobr**
Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [x] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [x] Is your initial contribution a single, squashed commit?

- [x] Does `gradlew build` run cleanly?

- [x] Have you written or updated unit tests to verify your changes?

- [n/a] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, check Concourse for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by alb3rtobr** [comment]
Thanks for the comment, I will add this rule to my "toolbox" XD

**Comment by jujoramos** [comment]
This might be a nit-pick... but I think it's better to use `tempFolderRule.getRoot().getAbsolutePath()` instead of `toString()` when trying to get the actual `String` representation of the root folder :-).

**Comment by kirklund** [comment]
@alb3rtobr @jujoramos If you need to use the `TemporaryFolder` from multiple DUnit JVMs then you can use the subclass `SerializableTemporaryFolder`. It'll serialize fine and is then usable from any JVM.

**Comment by alb3rtobr** [comment]
> @alb3rtobr @jujoramos If you need to use the `TemporaryFolder` from multiple DUnit JVMs then you can use the subclass `SerializableTemporaryFolder`. It'll serialize fine and is then usable from any JVM.

Do you think its needed in these tests? The folder is used to receive the exported logs zip files.

**Comment by kirklund** [comment]
@alb3rtobr I honestly don't know, but it doesn't hurt anything to change it to `SerializableTemporaryFolder`. You could just always use the `Serializable` and `Shareable` forms of any junit rules (if they exist) in dunit/distributed tests just in case.

**Pull request merged**
