### PR TITLE
GEODE-9910: Stopped embedded locator after failed start

### PR DESCRIPTION
**Pull request by boglesby**
### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [ ] Is your initial contribution a single, squashed commit?

- [ ] Does `gradlew build` run cleanly?

- [ ] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### CODE REVIEW

**Review by onichols-pivotal — COMMENTED** [review]
As per https://cwiki.apache.org/confluence/display/GEODE/Commit+Message+Format, first commit summary should be worded imperatively and additional detail paragraph(s) should describe the problem and how this change solves it.

By amending your initial commit and force-pushing now, you can benefit from review feedback on your commit message, and you won't have to remember to fix it later when you merge.

**Review by onichols-pivotal — COMMENTED** [review]
Thanks for improving your commit message!  Don't forget, first commit additional detail paragraph(s) should describe the problem and how this change solves it.

**Review by onichols-pivotal — COMMENTED** [review]
Thanks for writing a great commit message!

**Comment by jmelchio** [comment]
👍

**Comment by jmelchio** [comment]
👍

**Review by kirklund — APPROVED** [review]

**Pull request merged**
