### PR TITLE
GEODE-5878: Pass JAVA_HOME, GF_JAVA to test gfsh environment

### PR DESCRIPTION
**Pull request by PurelyApplied**
Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [x] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [x] Is your initial contribution a single, squashed commit?

- [x] Does `gradlew build` run cleanly?

- [existing failures] Have you written or updated unit tests to verify your changes?

- [n/a] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by rhoughton-pivot** [comment]
@onichols-pivotal Is this going to work for Java11 and Java8 tasks?

**Comment by pivotal-jbarrett** [comment]
Why invert the behavior we have? The approach should be as simple as making the Java a sub processes sees is the same one the parent process sees. Let gradle alone to do its magic of forking the correct Java.

**Comment by onichols-pivotal** [comment]
@pivotal-jbarrett the behavior we have is dangerous precisely because forking passes along the same JAVA_HOME.  This can cause the tests to inherit the compile JAVA_HOME, which is difficult to catch since the only symptom is passing tests.  Sure, we can painstakingly track down everywhere JAVA_HOME may be escaping currently.  Or we can make JAVA_HOME always be the test VM, and then we only have exactly 2 points to worry about making sure correct compile VM is used.

**Comment by onichols-pivotal** [comment]
I am trying out this PR in my pipeline.  It's taking a little longer than expected due to infrastructure issues.  Stay tuned.

**Comment by PurelyApplied** [comment]
Subsumed by #2643.

**Pull request closed without merging**
