### PR TITLE
GEODE-258: Remove deprecated Cache.getLoggerI18n and getSecurityLoggerI18n methods	

### PR DESCRIPTION
**Pull request by davinash**

### CODE REVIEW

**Comment by upthewaterspout** [comment]
I'm not quite sure about this one. LogWriter and LoggerI18n are also deprecated. I believe they were deprecated because geode is now using log4j2.

@dschneider-pivotal  - It looks like this PR contains the changes suggested in the ticket, but is just removing these two methods really what we want to do?

My other query is that log4j2 was introduced fairly recently, so is it too soon to remove LogWriter and LogWriterI18n?

**Comment by kirklund** [comment]
I think you should the log statements to use Log4j2 loggers instead of changing them to use a different getLogWriter() API. This work was started in 2014 and was never finished.

To convert a class to use Logger, do the following:
```java
import org.apache.logging.log4j.Logger;
import org.apache.geode.internal.logging.LogService;
...
private static final Logger logger = LogService.getLogger();
```
And then change blocks like this:
```java
if ((logger != null) && logger.fineEnabled()) {
  logger.fine("RegionSubRegionSnapshot Region entry count =" + this.entryCount + " for region =" + this.name);
```

To this:
```java
if (logger.isDebugEnabled()) {
  logger.debug("RegionSubRegionSnapshot Region entry count ={} for region ={}",  this.entryCount, this.name);
```

**Comment by davinash** [comment]
Thanks @kirklund and @upthewaterspout If I understand correctly getLoggerI18n should go away and replace with Log4j2. What is to be done for getSecurityLoggerI18n ??

**Comment by kirklund** [comment]
@davinash Sorry to take so long to respond! For the security logger you can use this:
```java
  private static Logger securityLogger = LogService.getLogger(LogService.SECURITY_LOGGER_NAME);
```
At some point, we should add this to LogService (feel free to add this if you want to):
```java
  public static Logger getSecurityLogger() {
    return getLogger(LogService.SECURITY_LOGGER_NAME);
  }
```
Then you could use:
```java
  private static Logger securityLogger = LogService.getSecurityLogger();
```

**Comment by davinash** [comment]
Thanks @kirklund  and @upthewaterspout for your comments. I am moving this discussion on  JIRA GEODE-258 and more questions.

**Comment by galen-pivotal** [comment]
Closing due to age and inactivity.

**Pull request closed without merging**
