### PR TITLE
Feature/geode 3411 Monitor the neighbour JVM using neihbour's member-timeout

### PR DESCRIPTION
**Pull request by aravindmusigumpula**
Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X ] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [X ] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [X ] Is your initial contribution a single, squashed commit?

- [X ] Does `gradlew build` run cleanly?

- [X ] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by kohlmu-pivotal** [comment]
@aravindmusigumpula could you please explain why this feature is required and why the member now has to adhere to his neighbor's member-timeout.

What problem is this change addressing and how would this change improve the member-timeout suspect member notification.

**Comment by aravindmusigumpula** [comment]
thanks @upthewaterspout for pointing out these issues ,
I have added this new parameter in two methods toDataPre_GFE_7_1_0_0, toDataPre_GFE_9_0_0_0.
And I understand that adding a field to toDataPre_GFE_7_1_0_0 breaks compatibility with client/peers, so should I remove it from this method?
I don't see any method toDataPre_GEODE_1_3_0_0, should I create one?
I am new here, please help me understand how to make this correct without breaking compatibility issues.

**Comment by bschuchardt** [comment]
It's inappropriate to change the meaning of member-timeout like this.  All timeouts in the distributed-system settings are currently settings concerning other members.  Instead I think you should deprecate member-timeout, ack-wait-threshold and ack-severe-alert-threshold.  Add a new setting and base internal ack-wait-threshold & ack-severe-alert-threshold as multiples of that setting.  You've brought the discussion to the dev list & I think that's a good place to hammer out the details.

Also, don't modify InternalDistributedMember.  Put any new member information in NetView.  InternalDistributedMembers are serialized in a lot of messages and are already way too big.  That affects performance.

There's a page describing on-wire backward compatibility under Code Contributions on the wiki: https://cwiki.apache.org/confluence/display/GEODE/Managing+Backward+Compatibility
That describes the toDataPre stuff that Dan was talking about.

This page describes how to write backward compatibility tests: https://cwiki.apache.org/confluence/display/GEODE/Writing+Backward-compatibility+DUnit+tests
You can find examples in the repo by searching for uses of the class VersionManager.

**Comment by aravindmusigumpula** [comment]
Thanks Bruce for suggestions, I will change the new variables from InternalDistributedMember to NetView and do changes related to backward compatibility.

Now I know that there is another way that member can be removed from the view i.e if any member is sending a message and waits for ack-wait-threshold, if there is no response from the target the sender will do final check and remove it from the view if there is still no response. 
But I don't understand how deprecating the settings member-timeout, ack-wait-threshold, ack-severe-alert-threshold into one will solve the problem. The main problem is that we want a member to survive in the view for longer time than others.

If we deprecate the settings into one setting and pass the setting to monitoring member(say A), then it will use the target member(say B which we want to survive in view for longer time) timeout for health monitoring and ack-wait-threshold to wait for the response for any message before doing final check.
But what if some other member(say C) which is monitoring any other member(say D) have the member-timeout and ack-wait-threshold some smaller values. So if member C messages to B, C uses the smaller value of ack-wait-threshold(which is of member D) to get a response and does the final check again on basis of smaller member-timeout. So still member B can be kicked out of the view in small amount of time.

I think this can be solved simply if we use the member-timeout of suspected member in the final check where we establish TCP connection. We don't need to club those three settings as well. We can set the member-timeout of a particular member to a higher value and the member which monitors it uses its own member-timeout as it is now, but during the final check it uses the suspected member-timeout(which is a greater value). The final check is common place in both the no heartbeat scenario and no response for a message scenario.

Are there any concerns around this new proposal ?

**Comment by aravindmusigumpula** [comment]
I have opened an another pull request which includes the new solution https://github.com/apache/geode/pull/1075 .

**Comment by aravindmusigumpula** [comment]
I am closing this pull request ( #717 ) as i have opened an other (#1075 ) for ticket GEODE-3411

**Pull request closed without merging**
