### PR TITLE
[GEODE-165] Fix for Add build support for generating antlr classes from grammar

### PR DESCRIPTION
**Pull request by davinash**
1. Updated spotless configuration to exclude 'generated-src' directory.
2. Removed
      OQLLexerTokenTypes.java
      OQLLexerTokenTypes.txt
      OQLParser.java
      OQLLexer.java
3. Removed above files entry from rat 

Thanks @metatype for helping in gradle configuration.

### CODE REVIEW

**Comment by upthewaterspout** [comment]
+1 Awesome!!!

**Comment by davinash** [comment]
Thanks @upthewaterspout , Is this PR good for merge to develop now.

**Comment by upthewaterspout** [comment]
Yeah, I think it's good to go.

**Comment by agingade** [comment]
Earlier the files used to be generated when the grammar files are changed (which was a rare case); with this change are we generating the files, every time when the build/compilation is done?

**Comment by upthewaterspout** [comment]
@agingade  - Yeah, they'll get generated every time you do a clean followed a by a build. Presumably if you don't do a clean the antlr plugin will detect if the files are up to date.

Prior to this fix I don't think there was even a README on how to generate these files. This fix is really the ideal solution - generated files should never be checked in to the source. This way everyone knows they need to modify oql.g, and everyone knows how to generate the resulting files because it happens automatically as part of the build.

**Comment by scmbuildguy** [comment]
+1 - I agree with generating these files should be done at build time and not checked into source.

**Pull request closed without merging**
