### PR TITLE
GEODE-6588: Mass cleanup of static analyzer warnings.

### PR DESCRIPTION
**Pull request by pivotal-jbarrett**
Happy Holidays!

The only gutter that should be so colorful is the one on your home for the holidays and not the warnings gutter in IntelliJ.

### CODE REVIEW

**Review by onichols-pivotal — APPROVED** [review]

**Review by rhoughton-pivot — APPROVED** [review]

**Review by dschneider-pivotal — APPROVED** [review]

**Comment by DonalEvans** [comment]
While it's not actually gating new PRs right now due to some implementation issues, there was a vote that passed to make the LGTM pre-checkin job a gating step, so in the spirit of that, could the two remaining alerts either be fixed or suppressed as false positives (with explanatory comments) please?

**Comment by pivotal-jbarrett** [comment]
> While it's not actually gating new PRs right now due to some implementation issues, there was a vote that passed to make the LGTM pre-checkin job a gating step, so in the spirit of that, could the two remaining alerts either be fixed or suppressed as false positives (with explanatory comments) please?

Both of those have been suppressed, following their Java suppression guide, and tickets for the false-positive issues have been opened. Unfortunately it looks like their Java suppression technique is also broken.

**Review by kamilla1201 — APPROVED** [review]

**Review by DonalEvans — APPROVED** [review]
Approving without checking all the files, as GitHub keeps lagging out when I try to view them. Thanks for doing such a comprehensive cleanup. Out of curiosity, do you know how many warnings were fixed with this PR?

**Review by mhansonp — APPROVED** [review]
Looks good for the parts I read

**Comment by kirklund** [comment]
I'm trying to add my approval, but github prevents me from getting to review dialog with:
```
Oh My
Sorry, this file list is taking too long to generate.
```
And it never finishes loading or presenting the dialog for submitting the review.

Is there a way to submit a review/approval without going through the standard gui that hits the above?

**Comment by DonalEvans** [comment]
> I'm trying to add my approval, but github prevents me from getting to the review dialog with:
> 
> ```
> Oh My
> Sorry, this file list is taking too long to generate.
> ```
> 
> And it never finishes loading or presenting the dialog for submitting the review.
> 
> Is there a way to submit a review/approval without going through the standard gui that hits the above?

@kirklund One potential workaround would be to use the github CLI: https://cli.github.com/manual/gh_pr_review

**Comment by pivotal-jbarrett** [comment]
@kirklund and others, I wouldn't focus too deep into each file. The changes are automated IntelliJ cleanups across the entire codebase. Think of it along the same lines as a mass "reformat" change.

**Review by kirklund — APPROVED** [review]

**Comment by kirklund** [comment]
Looks like merging of #7217 caused the two conflicts:
* geode-core/src/main/java/org/apache/geode/management/internal/JmxRmiOpenTypesSerialFilter.java was deleted
* geode-core/src/main/java/org/apache/geode/management/internal/ManagementAgent.java is now using classes that moved from geode-core to geode-serialization (and may have been renamed)

**Comment by pivotal-jbarrett** [comment]
> Looks like merging of #7217 caused the two conflicts:
> 
> * geode-core/src/main/java/org/apache/geode/management/internal/JmxRmiOpenTypesSerialFilter.java was deleted
> * geode-core/src/main/java/org/apache/geode/management/internal/ManagementAgent.java is now using classes that moved from geode-core to geode-serialization (and may have been renamed)

Yeah, this PR gets merge conflicts daily since it touches everything. I will rebase later.

**Review by jchen21 — APPROVED** [review]

**Review by jdeppe-pivotal — APPROVED** [review]

**Review by nabarunnag — APPROVED** [review]

**Review by mivanac — APPROVED** [review]

**Review by jinmeiliao — APPROVED** [review]

**Review by gesterzhou — APPROVED** [review]

**Pull request merged**
