### PR TITLE
GEODE-8997: remove protobuf client server code

### PR DESCRIPTION
**Pull request by bschuchardt**
This removes the experimental Protobuf-based client/server subproject
and associated files.  Protobuf is no longer included as a Geode dependency.

Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [x] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [x] Is your initial contribution a single, squashed commit?

- [x] Does `gradlew build` run cleanly?

- [ ] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, check Concourse for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Review by DonalEvans — APPROVED** [review]
Approving for the two files I'm code owner for in this PR.

**Review by kohlmu-pivotal — DISMISSED** [review]
I'm not sure when it was decided that Geode was not to support Protobuf any more. Please point me at the dev list thread.

**Comment by bschuchardt** [comment]
> I'm not sure when it was decided that Geode was not to support Protobuf any more. Please point me at the dev list thread.

good question Udo.  There hasn't been open discussion about removing this and there should be.

**Review by rhoughton-pivot — APPROVED** [review]

**Review by onichols-pivotal — APPROVED** [review]

**Review by nabarunnag — APPROVED** [review]
LGTM

**Review by Bill — APPROVED** [review]
Approved

**Review by jinmeiliao — APPROVED** [review]

**Review by jdeppe-pivotal — APPROVED** [review]

**Review by kirklund — APPROVED** [review]
The changes for removal all look good.

**Review by jdeppe-pivotal — CHANGES_REQUESTED** [review]
I'm going to reverse my original decision on this, pending further discussion...

**Review by jdeppe-pivotal — APPROVED** [review]

**Review by echobravopapa — APPROVED** [review]
Less Code is Better Code :tm:

**Review by agingade — APPROVED** [review]

**Pull request merged**
