### PR TITLE
Bump archunit from 0.12.0 to 0.14.1

### PR DESCRIPTION
**Pull request by onichols-pivotal**
Adopt me! (otherwise I will be abandoned if no progress by Oct 16)

### CODE REVIEW

**Comment by kirklund** [comment]
UnitTest failures:
```
> Task :geode-serialization:test

org.apache.geode.internal.serialization.SerializationDependenciesJUnitTest > serializationDoesntDependOnCoreProvisional FAILED
    java.lang.AssertionError: Architecture Violation [Priority: MEDIUM] - Rule 'classes that reside in a package 'org.apache.geode.internal.serialization..' should only depend on classes that reside in a package 'org.apache.geode.internal.serialization..' or not reside in a package 'org.apache.geode..' or reside in a package 'org.apache.geode.test..'' was violated (45 times):
    Class <org.apache.geode.internal.serialization.KnownVersion> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.DscodeHelper.dscodes> is annotated with <org.apache.geode.annotations.Immutable> in (DscodeHelper.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.CURRENT> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.CURRENT_ORDINAL> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GEODE_1_10_0> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GEODE_1_11_0> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GEODE_1_12_0> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GEODE_1_13_0> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GEODE_1_14_0> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GEODE_1_1_0> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GEODE_1_1_1> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GEODE_1_2_0> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GEODE_1_3_0> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GEODE_1_4_0> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GEODE_1_5_0> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GEODE_1_6_0> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GEODE_1_7_0> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GEODE_1_8_0> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GEODE_1_9_0> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GFE_56> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GFE_57> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GFE_58> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GFE_603> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GFE_61> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GFE_6516> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GFE_651> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GFE_65> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GFE_6622> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GFE_662> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GFE_66> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GFE_701> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GFE_7099> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GFE_70> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GFE_71> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GFE_8009> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GFE_80> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GFE_81> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GFE_82> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.GFE_90> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.TEST_VERSION> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.TOKEN> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.KnownVersion.VALUES> is annotated with <org.apache.geode.annotations.Immutable> in (KnownVersion.java:0)
    Field <org.apache.geode.internal.serialization.StaticSerialization.threadLocalByteArrayCache> is annotated with <org.apache.geode.annotations.internal.MakeNotStatic> in (StaticSerialization.java:0)
    Field <org.apache.geode.internal.serialization.internal.DSFIDSerializerImpl.dsfidMap2> is annotated with <org.apache.geode.annotations.Immutable> in (DSFIDSerializerImpl.java:0)
    Field <org.apache.geode.internal.serialization.internal.DSFIDSerializerImpl.dsfidMap> is annotated with <org.apache.geode.annotations.Immutable> in (DSFIDSerializerImpl.java:0)

> Task :geode-serialization:test FAILED
```
```
> Task :geode-tcp-server:test

org.apache.geode.distributed.internal.tcpserver.TcpServerDependenciesTest > membershipDoesntDependOnCoreProvisional FAILED
    java.lang.AssertionError: Architecture Violation [Priority: MEDIUM] - Rule 'classes that reside in a package 'org.apache.geode.distributed.internal.tcpserver..' should only depend on classes that reside in a package 'org.apache.geode.distributed.internal.tcpserver..' or reside in a package 'org.apache.geode.internal.serialization..' or reside in a package 'org.apache.geode.logging.internal.log4j.api..' or reside in a package 'org.apache.geode.logging.internal.executors..' or not reside in a package 'org.apache.geode..' or reside in a package 'org.apache.geode.test..'' was violated (2 times):
    Field <org.apache.geode.distributed.internal.tcpserver.TcpServer.GOSSIP_TO_GEMFIRE_VERSION_MAP> is annotated with <org.apache.geode.annotations.internal.MutableForTesting> in (TcpServer.java:0)
    Field <org.apache.geode.distributed.internal.tcpserver.TcpSocketFactory.DEFAULT> is annotated with <org.apache.geode.annotations.Immutable> in (TcpSocketFactory.java:0)

16 tests completed, 1 failed

> Task :geode-tcp-server:test FAILED
```

**Comment by kirklund** [comment]
IntegrationTest failures:
```
> Task :geode-membership:integrationTest

org.apache.geode.distributed.internal.membership.api.MembershipAPIArchUnitTest > membershipAPIDoesntDependOnMembershipORCore FAILED
    java.lang.AssertionError: Architecture Violation [Priority: MEDIUM] - Rule 'classes that reside in a package 'org.apache.geode.distributed.internal.membership.api' should only depend on classes that reside in a package 'org.apache.geode.distributed.internal.membership.api' or not reside in a package 'org.apache.geode..' or reside in a package 'org.apache.geode.internal.serialization..' or reside in a package 'org.apache.geode.distributed.internal.tcpserver..' or type org.apache.geode.distributed.internal.membership.gms.MembershipBuilderImpl or type org.apache.geode.distributed.internal.membership.gms.MembershipLocatorBuilderImpl or type org.apache.geode.distributed.internal.membership.gms.MemberDataBuilderImpl or type org.apache.geode.distributed.internal.membership.gms.MemberIdentifierImpl or type org.apache.geode.internal.inet.LocalHostUtil' was violated (2 times):
    Field <org.apache.geode.distributed.internal.membership.api.MembershipConfig.DEFAULT_MEMBERSHIP_PORT_RANGE> is annotated with <org.apache.geode.annotations.internal.MakeImmutable> in (MembershipConfig.java:0)
    Field <org.apache.geode.distributed.internal.membership.api.Message.ALL_RECIPIENTS> is annotated with <org.apache.geode.annotations.Immutable> in (Message.java:0)
```
```
> Task :geode-membership:integrationTest

org.apache.geode.distributed.internal.membership.MembershipDependenciesJUnitTest > membershipDoesntDependOnCoreProvisional FAILED
    java.lang.AssertionError: Architecture Violation [Priority: MEDIUM] - Rule 'classes that reside in a package 'org.apache.geode.distributed.internal.membership.gms..' should only depend on classes that reside in a package 'org.apache.geode.distributed.internal.membership.gms..' or reside in a package 'org.apache.geode.distributed.internal.membership.api..' or reside in a package 'org.apache.geode.internal.serialization..' or reside in a package 'org.apache.geode.logging.internal..' or reside in a package 'org.apache.geode.distributed.internal.tcpserver..' or reside in a package 'org.apache.geode.internal.inet..' or reside in a package 'org.apache.geode.internal.lang..' or not reside in a package 'org.apache.geode..' or type org.apache.geode.internal.AvailablePortHelper or reside in a package 'org.apache.geode.test..'' was violated (14 times):
    Field <org.apache.geode.distributed.internal.membership.gms.GMSMembership.inhibitForceDisconnectLogging> is annotated with <org.apache.geode.annotations.internal.MakeNotStatic> in (GMSMembership.java:0)
    Field <org.apache.geode.distributed.internal.membership.gms.GMSMembershipView.RANDOM> is annotated with <org.apache.geode.annotations.Immutable> in (GMSMembershipView.java:0)
    Field <org.apache.geode.distributed.internal.membership.gms.MemberIdentifierImpl.dsfidVersions> is annotated with <org.apache.geode.annotations.Immutable> in (MemberIdentifierImpl.java:0)
    Field <org.apache.geode.distributed.internal.membership.gms.membership.GMSJoinLeave.currentView> is annotated with <org.apache.geode.annotations.VisibleForTesting> in (GMSJoinLeave.java:0)
    Field <org.apache.geode.distributed.internal.membership.gms.membership.GMSJoinLeave.isCoordinator> is annotated with <org.apache.geode.annotations.VisibleForTesting> in (GMSJoinLeave.java:0)
    Method <org.apache.geode.distributed.internal.membership.gms.GMSMembership.forceDisconnect(java.lang.String)> is annotated with <org.apache.geode.annotations.VisibleForTesting> in (GMSMembership.java:0)
    Method <org.apache.geode.distributed.internal.membership.gms.MemberIdentifierImpl.setUniqueTag(java.lang.String)> is annotated with <org.apache.geode.annotations.VisibleForTesting> in (MemberIdentifierImpl.java:0)
    Method <org.apache.geode.distributed.internal.membership.gms.Services.registerSerializables(org.apache.geode.internal.serialization.DSFIDSerializer)> is annotated with <org.apache.geode.annotations.VisibleForTesting> in (Services.java:0)
    Method <org.apache.geode.distributed.internal.membership.gms.locator.GMSLocator.getMembers()> is annotated with <org.apache.geode.annotations.VisibleForTesting> in (GMSLocator.java:0)
    Method <org.apache.geode.distributed.internal.membership.gms.locator.GMSLocator.getViewFile()> is annotated with <org.apache.geode.annotations.VisibleForTesting> in (GMSLocator.java:0)
    Method <org.apache.geode.distributed.internal.membership.gms.locator.GMSLocator.setViewFile(java.io.File)> is annotated with <org.apache.geode.annotations.VisibleForTesting> in (GMSLocator.java:0)
    Method <org.apache.geode.distributed.internal.membership.gms.locator.MembershipLocatorImpl.getGMSLocator()> is annotated with <org.apache.geode.annotations.VisibleForTesting> in (MembershipLocatorImpl.java:0)
    Method <org.apache.geode.distributed.internal.membership.gms.membership.GMSJoinLeave.getMinimumRetriesBeforeBecomingCoordinator(int)> is annotated with <org.apache.geode.annotations.VisibleForTesting> in (GMSJoinLeave.java:0)
    Method <org.apache.geode.distributed.internal.membership.gms.membership.GMSJoinLeave.recordViewRequest(org.apache.geode.distributed.internal.membership.gms.messages.AbstractGMSMessage)> is annotated with <org.apache.geode.annotations.VisibleForTesting> in (GMSJoinLeave.java:0)
```
```
> Task :geode-membership:integrationTest FAILED

timeout exceeded
```

**Comment by Bill** [comment]
I pushed three commits that I think address all the issues @kirklund mentioned in comments above.

A better longer-term fix would be to define "layers" for each of our, ahem, layers. For now I just added allowances for the annotations package in the `geode-commons` "module".

**Comment by Bill** [comment]
whacked another mole

**Review by Bill — APPROVED** [review]
Approved!

**Pull request merged**
