### PR TITLE
GEODE-3718: InternalResourceManager thread pool shutdown improvement

### PR DESCRIPTION
**Pull request by mivanac**
Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [*] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [*] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [*] Is your initial contribution a single, squashed commit?

- [*] Does `gradlew build` run cleanly?

- [x] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, check Concourse for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by mivanac** [comment]
According to documentation:
shutdown(): - Initiates an orderly shutdown in which previously submitted tasks are executed, but no new tasks will be accepted. Invocation has no additional effect if already shut down. 

After shutdown is triggered, we are waiting  max 120 secs for pending tasks to finish. If after that time interval, pool is still not terminated, my proposal is,  to trigger 
shutdownNow(): - Attempts to stop all actively executing tasks, halts the processing of waiting tasks, and returns a list of the tasks that were awaiting execution.

My question is, what is expected to be solution:
- shorten waiting time interval
- or after waiting for initial 120 secs, shutdown all pending tasks

**Comment by dschneider-pivotal** [comment]
The original ticket was reporting that we hung in the code that I think would have timed out after 120 seconds. This was so long that it gave the appearance of a hang. I think it ends up waiting for 120 seconds because one of the recovery delay task is probably still sleeping waiting for its time to expire.
I think we want to find a way to cancel this particular task without forcing all other tasks in this executor to be immediately terminated. One possible solution is for the recovery delay task to be scheduled to run after the recovery delay. I don't think executors wait for jobs that are scheduled to run in the future when it is shutdown. But the first thing we need is a test that demonstrates that configuring a recovery delay will cause this 120 second hang during shutdown.

**Comment by boglesby** [comment]
This code change is after the issue has already happened. We can do this, but it doesn't address the issue.

The issue is that when a member is stopped, the shutdown hook attempts to stop the InternalResourceManager's scheduledExecutor. If that executor has any pending tasks (including ones in the future), the shutdown hook blocks waiting for them to fire.

If I run this test:

1. Start 3 servers defining a partitioned region with recovery-delay > 0
2. Load some data into the partitioned region
3. Kill one server using kill -9
4. The remaining servers schedule the recovery task
5. Stop the remaining servers normally (the JVMs do not stop)

The shutdown hook thread is waiting here for the InternalResourceManager's scheduledExecutor to terminate:
```
"Distributed system shutdown hook" #12 prio=5 os_prio=31 tid=0x00007ff0f8c33000 nid=0x12307 waiting on condition [0x000070000bc11000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000766c00038> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1465)
	at org.apache.geode.internal.cache.control.InternalResourceManager.stopExecutor(InternalResourceManager.java:343)
	at org.apache.geode.internal.cache.control.InternalResourceManager.close(InternalResourceManager.java:156)
	at org.apache.geode.internal.cache.GemFireCacheImpl.close(GemFireCacheImpl.java:2079)
	- locked <0x0000000766665b58> (a java.lang.Class for org.apache.geode.internal.cache.GemFireCacheImpl)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.disconnect(InternalDistributedSystem.java:1516)
	- locked <0x0000000766665b58> (a java.lang.Class for org.apache.geode.internal.cache.GemFireCacheImpl)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.lambda$static$6(InternalDistributedSystem.java:2181)
	at org.apache.geode.distributed.internal.InternalDistributedSystem$$Lambda$8/111900554.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```
InternalResourceManager.stopExecutor waits up to 120 seconds to stop:
```
void stopExecutor(ExecutorService executor) {
  if (executor == null) {
    return;
  }
  executor.shutdown();
  final int secToWait = Integer
      .getInteger(DistributionConfig.GEMFIRE_PREFIX + "prrecovery-close-timeout", 120).intValue();
  try {
    executor.awaitTermination(secToWait, TimeUnit.SECONDS);
  } catch (InterruptedException x) {
    Thread.currentThread().interrupt();
    logger.debug("Failed in interrupting the Resource Manager Thread due to interrupt");
  }
  if (!executor.isTerminated()) {
    logger.warn("Failed to stop resource manager threads in {} seconds",
        secToWait);
  }
}
```
I added some logging that shows the sequence of events.

The logging shows the redundancy recovery task being scheduled when the first server is killed (steps 3 and 4 above):
```
[warn 2019/06/24 14:09:21.014 PDT <DM-MemberEventInvoker> tid=0x15] PRHARedundancyProvider.scheduleRedundancyRecovery about to schedule task with delay=30000
```
Then, the shutdown hook is invoked when the server is stopped which causes the InternalResourceManager to wait. The 1 task below is the redundancy recovery task:
```
[info 2019/06/24 14:09:25.161 PDT <Distributed system shutdown hook> tid=0xc] VM is exiting - shutting down distributed system

[info 2019/06/24 14:09:25.173 PDT <Distributed system shutdown hook> tid=0xc] GemFireCache[id = 1850680894; isClosing = true; isShutDownAll = false; created = Mon Jun 24 14:08:40 PDT 2019; server = false; copyOnRead = false; lockLease = 120; lockTimeout = 60]: Now closing.

[warn 2019/06/24 14:09:25.174 PDT <Distributed system shutdown hook> tid=0xc] InternalResourceManager.stopExecutor waiting up to 120 seconds to terminate ScheduledThreadPoolExecutor containing 1 task
```
Then, the redundancy recovery task attempts to execute, but a CacheClosedException is thrown, so it doesn't do anything:
```
[warn 2019/06/24 14:09:51.016 PDT <ResourceManagerRecoveryThread 1> tid=0xb2] PRHARedundancyProvider.run2 about to start recovery

[warn 2019/06/24 14:09:51.016 PDT <ResourceManagerRecoveryThread 1> tid=0xb2] PRHARedundancyProvider.run2 caught:
org.apache.geode.cache.CacheClosedException: The cache is closed.
	at org.apache.geode.internal.cache.GemFireCacheImpl$Stopper.generateCancelledException(GemFireCacheImpl.java:1482)
	at org.apache.geode.CancelCriterion.checkCancelInProgress(CancelCriterion.java:83)
	at org.apache.geode.internal.cache.GemFireCacheImpl.getInternalResourceManager(GemFireCacheImpl.java:4302)
	at org.apache.geode.internal.cache.GemFireCacheImpl.getResourceManager(GemFireCacheImpl.java:4291)
	at org.apache.geode.internal.cache.control.InternalResourceManager.getInternalResourceManager(InternalResourceManager.java:102)
	at org.apache.geode.internal.cache.partitioned.PartitionedRegionRebalanceOp.execute(PartitionedRegionRebalanceOp.java:154)
	at org.apache.geode.internal.cache.PRHARedundancyProvider$3.run2(PRHARedundancyProvider.java:1600)
	at org.apache.geode.internal.cache.partitioned.RecoveryRunnable.run(RecoveryRunnable.java:59)
	at org.apache.geode.internal.OneTaskOnlyExecutor$DelegatingRunnable.run(OneTaskOnlyExecutor.java:142)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
Finally, the InternalResourceManager stops the executor:
```
[warn 2019/06/24 14:09:51.018 PDT <Distributed system shutdown hook> tid=0xc] InternalResourceManager.stopExecutor terminated
```
It looks like there are a few things that can be done to address this:

1. Don't wait to shutdown the executor. Just shut it down immediately. I'm not sure the consequences of this. In the above case, I'm not sure there are any, but there are other cases.
2. Don't schedule the redundancy recovery task for sometime in the future. Wait for the future to arrive and then schedule it. Darrel suggested this in one of his comments.

**Comment by dschneider-pivotal** [comment]
Another possible fix would be to have "secToWait" default to 1 instead of 120 and then, as mivanac proposed, call shutdownNow. That gives running threads 1 second to finish before we interrupt them by calling shutdownNow.

**Comment by mivanac** [comment]
Added test, and updated solution according to Darrels proposal

**Comment by mivanac** [comment]
Thanks for comments and test.

**Comment by mhansonp** [comment]
Given this has been approved by all reviewers, are we ready to merge this?

**Pull request merged**
