### PR TITLE
GEODE-9859: Do not copy entry if it is a destroyed entry

### PR DESCRIPTION
**Pull request by albertogpz**
### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [ ] Is your initial contribution a single, squashed commit?

- [ ] Does `gradlew build` run cleanly?

- [ ] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### CODE REVIEW

**Review by nabarunnag — CHANGES_REQUESTED** [review]
A small unit test along with this PR may be needed.

**Comment by albertogpz** [comment]
> A small unit test along with this PR may be needed.

@nabarunnag Could you please review the PR?

**Comment by albertogpz** [comment]
> A small unit test along with this PR may be needed.

@nabarunnag Are you ok with the unit test added? Any other thing to change?

**Comment by agingade** [comment]
@albertogpz Any plans of merging this PR. Also there is a new ticket created in the same area GEODE-9984 can you please look into that (and take ticket ownership)

**Comment by albertogpz** [comment]
> @albertogpz Any plans of merging this PR. Also there is a new ticket created in the same area GEODE-9984 can you please look into that (and take ticket ownership)

@agingade I would like to merge but I still need the approval from @nabarunnag

**Review by nabarunnag — APPROVED** [review]

**Pull request merged**
