### PR TITLE
GEODE-8546: added retry create buckets in case colocation is not comp…

### PR DESCRIPTION
**Pull request by mivanac**
Co-authored-by: Mario Kevo mario.kevo@est.tech

Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [*] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [*] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [*] Is your initial contribution a single, squashed commit?

- [*] Does `gradlew build` run cleanly?

- [ ] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, check Concourse for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Review by DonalEvans — CHANGES_REQUESTED** [review]
These changes do not include a test that confirms the fix. Per the [Criteria for Code Submissions](https://cwiki.apache.org/confluence/display/GEODE/Criteria+for+Code+Submissions), changes must be accompanied by a test that reproduces the issue and fails without the included changes, to confirm that the changes are valid. Please write a test that demonstrates the issue described in the ticket and that passes when then changes in this PR are applied.

**Comment by kohlmu-pivotal** [comment]
@mivanac is this PR is still relevant or can it be closed?

**Comment by mkevo** [comment]
Hi @kohlmu-pivotal ,

We are trying to write a test, but without success.
@DonalEvans suggest us to use **PartitionListener interface**, specifically, overriding the afterBucketCreated() method to artificially slow down colocation and make it possible to hit the issue more easily. But we don't have an idea how to slow down colocation. We hit the issue only if we add sleep for more than 15 seconds, but it is hardcoded and fix will not working it as it will always wait for hardcoded value.
If you or someone else can help with this, we will appreciate it. If you want I can send you detail steps how to reproduce the issue locally via mail.

**Comment by kohlmu-pivotal** [comment]
@DonalEvans Do you have any capacity to assist with this?

**Comment by DonalEvans** [comment]
> @DonalEvans Do you have any capacity to assist with this?

I emailed back and forth with Mario a bit trying to figure out a way to reproduce the issue in a DUnit test, but it's not an area of the code I'm particularly familiar with so my ability to help was fairly limited. I thought that if the assumption that the problem was caused by colocation taking too long was correct, then artificially slowing down colocation by using a listener to wait a little after each bucket is created could reproduce it.

Since part of the proposed fix seems to be to wait a total of 9000ms for colocation to complete in `CreateMIssingBucketTask.java`, it seems like forcing colocation to take close to that long should be a sure-fire way to reproduce the issue, if the fix is effective. It seems like this wasn't the case though, so maybe my idea was off the mark.

**Comment by mkevo** [comment]
I tried to write a test on different ways but without success.
If you know someone who possible can help me with this, I will appreciate it.
It is also hard to reproduce it manually, so I think that it will be more harder to create test for it.

**Comment by onichols-pivotal** [comment]
This PR has been inactive for some while, can it be closed?

**Comment by mkevo** [comment]
This PR is waiting for a help, as I said it is hard to reproduce it manually too. I tried the different ways to reproduce it, but without success.
With Donal suggestion I can get the problematic log, but it is some kind of hardcoding so fix will not help there, but in the real case fix will help.

**Comment by onichols-pivotal** [comment]
This PR has been open for some while with no recent activity.  Please keep Geode tidy by closing PRs you're not actively using.

**Comment by mkevo** [comment]
@onichols-pivotal,
I have some problems with writing the test and some help will be useful.

**Comment by onichols-pivotal** [comment]
I can see how this could be tricky.  Reaching out to the geode dev list might help.

**Comment by onichols-pivotal** [comment]
This PR has been untouched for several months, should it be closed?

**Comment by mkevo** [comment]
> This PR has been untouched for several months, should it be closed?

Still waiting for a some help to write a test.

**Comment by onichols-pivotal** [comment]
this PR appears to be abandoned, can it be closed?

**Pull request closed without merging**
