### PR TITLE
GEODE-2953: Imports optimized in every file with a wildcard import.

### PR DESCRIPTION
**Pull request by PurelyApplied**
This is a purely semantic change.  Imports have been optimized by my IDE.  This may have the side-effect of changing some imports to static imports where applicable, as well as the ongoing disagreement between IntelliJ and Eclipse as to where `java` and `javax` imports belong.

All the same, precheckin up and running.  Tests and Legacy already back green.

### CODE REVIEW

**Comment by PurelyApplied** [comment]
Please review the diff, or run a regex search matching `import .*\*;\n`.  This regex hits 1024 occurrences in production and 2205 occurrences in test code.

Some of these occurrences are commented out.  Matching `^import .*\*;\n` hits 827 production and 2175 test occurrences.

1388 classes going against best practices is indeed alarming, but I do not believe it is incorrect.

**Comment by PurelyApplied** [comment]
Upon further inspection, it appears that I neglected a good number of the test files.  The PR has been updated and the commit message has been made more explicit.  However, this means this PR now touches 1,807 files...

**Comment by kohlmu-pivotal** [comment]
I really don't think that we should be doing this. Adds no value other than import reorganization....

**Comment by PurelyApplied** [comment]
Yeah, while I do firmly believe that there is value in good form and adherence to best practices, this PR ended up a lot bigger than I had initially expected.

**Pull request closed without merging**
