### PR TITLE
GEODE-9822: Quorum Calculation Requires Majority

### PR DESCRIPTION
**Pull request by Bill**
[GEODE-9822](https://issues.apache.org/jira/browse/GEODE-9822)

The membership quorum calculation doesn't require a majority. As a result, a two-locator cluster will have a split-brain during a network partition. This PR fixes the quorum calculation to ensure that a majority is required on the "winning" side.

- [x] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [x] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [x] Is your initial contribution a single, squashed commit?

- [x] Does `gradlew build` run cleanly?

- [x] Have you written or updated unit tests to verify your changes?

### CODE REVIEW

**Comment by Bill** [comment]
the most recent acceptance test failure is GEODE-9877

**Review by davebarnes97 — APPROVED** [review]
Doc change LGTM

**Review by dschneider-pivotal — APPROVED** [review]

**Review by kamilla1201 — APPROVED** [review]
Very important fix! This problem exists not only in the cluster of two equal-weight members but in any cluster with an even number of equal-weight members. Or more generally in a cluster with even weight.

**Comment by Bill** [comment]
In fact it's even slightly worse than that, @kamilla1201. Any set of members that can be partitioned (into more than one set), where any two-or-more, each still have 49% or more of the total weight, will result in a split-brain. How's that for a sentence?

**Pull request merged**
