### PR TITLE
GEODE-6112: Gfsh should respond to SIGINT

### PR DESCRIPTION
**Pull request by balesh2**
Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [ ] Is your initial contribution a single, squashed commit?

- [ ] Does `gradlew build` run cleanly?

- [ ] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by metatype** [comment]
@kirklund Do you know why SIGINT was being tossed?

**Comment by kirklund** [comment]
I think SpringShell which GFSH extends has or had a bug (possibly caused by the version of JLine it uses) which caused CTRL-C of GFSH to also terminate any processes that GFSH had launched. I'm not sure if this problem still exists. Jens may know more about it -- I think he was working on the signal handling mechanism in GFSH.

**Comment by balesh2** [comment]
That issue no longer exists because I have seen locator processes outlive gfsh. But there is another issue with this implementation, which is that ctrl-c with text in the prompt kills gfsh instead of just getting rid of the text like a normal terminal does, which would be extremely frustrating behavior as a user.

**Comment by balesh2** [comment]
Closing this until it is ready for PR.

**Pull request closed without merging**
