### PR TITLE
GEODE-6232: Disable JMX in PersistentPartitionedRegionRegressionTest

### PR DESCRIPTION
**Pull request by kirklund**
The cause of the hang in GEODE-6232 is lock ordering that involves JMX ManagementListener. Since PersistentPartitionedRegionRegressionTest does not need JMX, this change will disable JMX in the test.

Requires PR #3095 to be merged first. The commit in that PR is included in this PR's branch. Please review just the 2nd commit in this PR which changes PersistentPartitionedRegionRegressionTest to use disable-jmx.

### CODE REVIEW

**Comment by kirklund** [comment]
Prior to disabling JMX in the test, StressNewTest would fail (hanging on the deadlock) 100% in PRs that changed PersistentPartitionedRegionRegressionTest.

**Comment by jinmeiliao** [comment]
Are we adding this config property just to fix a test? Is this config property required for user to get a particular behavior when using PersistentPartitionedRegion? If not, I would say we either fix the test or get rid of the test.

**Comment by kirklund** [comment]
@jinmeiliao In my discussion with @upthewaterspout yesterday, I noted that fixing the underlying deadlock is going to take a large effort which I don't have time to do. The next option to fix PersistentPartitionedRegionRegressionTest is to bounce the DUnit VM instead of invoking Cache.close() within the callback where it's being called. Dan and I then decided it was best to disable JMX MBeans for the test because test doesn't need MBeans and this will prevent the test from hanging. The underlying deadlock would still need to be fixed but at least precheckin would not hang. I do not have time to do any further work on this. So my proposal is this: I'll close these PRs and reassign the Jira tickets to you. Should I reassign these tickets to you?

**Comment by kirklund** [comment]
@jinmeiliao @upthewaterspout The underlying deadlock is filed as [GEODE-6255: ManagementListener may deadlock with Cache close](https://issues.apache.org/jira/browse/GEODE-6255). The only code path I can find that deadlocks is:

* Thread-1 is invoking Cache.close()
* Thread-2 is invoking Region creation for a persistent Region that will use the default Disk Store which has not yet been created

**Comment by jinmeiliao** [comment]
@kirklund I wish I did not comment on this PR then :-). Just ignore my comment.

**Comment by kirklund** [comment]
@jinmeiliao It's a huge can of worms you don't want to go near. Trust me lol

**Pull request merged**
