### PR TITLE
GEODE-9969: Fix unescaping the region name with underscore

### PR DESCRIPTION
**Pull request by mkevo**
### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [x] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [x] Is your initial contribution a single, squashed commit?

- [x] Does `gradlew build` run cleanly?

- [x] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### CODE REVIEW

**Review by DonalEvans — APPROVED** [review]
Approving assuming the Windows Acceptance test passes.

**Comment by mkevo** [comment]
Hi @dschneider-pivotal,
This is the same PR as the one you approved before([#7282](https://github.com/apache/geode/pull/7282)) with the minor change, replacing double quotes with a single quote to pass test on the windows.
Can you please approved this so we can merge it?
Thanks!

**Comment by mkevo** [comment]
Hi @dschneider-pivotal,

Can you please re-review this PR?

BR,
Mario

**Comment by mkevo** [comment]
Hi @dschneider-pivotal,

Can you please add your review on this? 
The same PR as you approved before (#7282) with replacing double quotes with single quotes to pass tests on windows.

BR,
Mario

**Comment by mkevo** [comment]
Hi @dschneider-pivotal, @gesterzhou, @jchen21, @upthewaterspout,
Can someone add a review for the files you are CODEOWNER?
Thanks!

**Review by upthewaterspout — APPROVED** [review]
Definitely an improvement! 

I wonder if there are more issues lingering here. What happens if a region name ends with an _? Or there are two underscores in the middle of region name? It seems like we can never completely accurately unescape a PR path, because `escapePRPath` loses information - `/_` and `_/` will both become `___` in the escaped version. I wonder if it would be better to find a better way to get the PR name back that doesn't involve this "unescape" method.

**Pull request merged**
