### PR TITLE
GEODE-3075: initial flow adding the new client protocol to core.

### PR DESCRIPTION
**Pull request by galen-pivotal**
Create `ServerConnectionFactory`, which creates either instances of LegacyServerConnection (identical in functionality to the old `ServerConnection`) or `NewProtocolServerConnection` (which is currently basically a stub, but will never get called unless a feature flag is set).

This is the initial work for GEODE-3074, and will allow us to continue to work on further tasks for that project.

An explicit goal with this PR is to not disturb any existing functionality. Unless a feature flag is set *and* a connection with a certain magic byte is received, server connections will work as before. If you see something that you think may break, please let me know.

Have a nice day!

----
Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [x] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [ ] Is your initial contribution a single, squashed commit?

- [x] Does `gradlew build` run cleanly?

- [x] Have you written or updated unit tests to verify your changes?

- [n/a] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by bschuchardt** [comment]
I'm running precheckin on this PR & will merge it to develop when finished

**Comment by bschuchardt** [comment]
There was a failure in one of the new tests

:geode-core:integrationTest

org.apache.geode.internal.cache.tier.sockets.ServerConnectionFactoryIntegrationTest > testNewProtocolHeaderLeadsToNewProtocolServerConnection FAILED
    org.apache.geode.GemFireConfigException: The locators attribute can not be empty when the mcast-port attribute is non-zero.
        at org.apache.geode.distributed.internal.InternalDistributedSystem.initialize(InternalDistributedSystem.java:603)
        at org.apache.geode.distributed.internal.InternalDistributedSystem.newInstance(InternalDistributedSystem.java:350)
        at org.apache.geode.distributed.internal.InternalDistributedSystem.newInstance(InternalDistributedSystem.java:338)
        at org.apache.geode.distributed.internal.InternalDistributedSystem.newInstance(InternalDistributedSystem.java:330)
        at org.apache.geode.distributed.DistributedSystem.connect(DistributedSystem.java:205)
        at org.apache.geode.cache.CacheFactory.create(CacheFactory.java:217)
        at org.apache.geode.internal.cache.tier.sockets.ServerConnectionFactoryIntegrationTest.testNewProtocolHeaderLeadsToNewProtocolServerConnection(ServerConnectionFactoryIntegrationTest.java:50)

**Comment by galen-pivotal** [comment]
@bschuchardt Was that the only failure? It looks like another test had set `mcast-port` to a non-zero value and failed to clean up the environment

I'm rerunning precheckin; will continue working on top of this branch and hopefully this passes. If that's the only failure, I would think it should be safe to merge with the one-line added change.

**Comment by galen-pivotal** [comment]
This failed due to Spotless; closing in favor of #597.

**Pull request closed without merging**
