### PR TITLE
GEODE-8715: Redis INFO command 'Keyspace' section should not be present if no keys in database

### PR DESCRIPTION
**Pull request by jhutchison**
Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [ ] Is your initial contribution a single, squashed commit?

- [ ] Does `gradlew build` run cleanly?

- [ ] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, check Concourse for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Review by sabbey37 — CHANGES_REQUESTED** [review]
Seems good!  Just looks like it needs a Jira ticket.  [GEODE-8706](https://issues.apache.org/jira/projects/GEODE/issues/GEODE-8706) looks like it's for a different issue.

**Comment by jhutchison** [comment]
> Seems good! Just looks like it needs a Jira ticket. [GEODE-8706](https://issues.apache.org/jira/projects/GEODE/issues/GEODE-8706) looks like it's for a different issue.

so it does-  weird- not sure how that happened \_?_/ .   thanks- fixed.

**Comment by jhutchison** [comment]
> > Seems good! Just looks like it needs a Jira ticket. [GEODE-8706](https://issues.apache.org/jira/projects/GEODE/issues/GEODE-8706) looks like it's for a different issue.
> 
> so it does- weird- not sure how that happened _?_/ . thanks- fixed.

re-opened pr in https://github.com/apache/geode/pull/5753 with renamed branch and pr.  closing this pr.

**Comment by jhutchison** [comment]
mistakenly assigned unrelated ticket.  Pr closed and reopened in new pr https://github.com/apache/geode/pull/5753 with matching branch name

**Pull request closed without merging**
