### PR TITLE
GEODE-2980: All the methods in an interface are implicitly public and abstract.

### PR DESCRIPTION
**Pull request by davinash**
All fields in the interface are implicitly public, static and final.
Removing this from all the interface.
Pre-checkin pass.

Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [X] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [X] Is your initial contribution a single, squashed commit?

- [X] Does `gradlew build` run cleanly?

- [ ] Have you written or updated unit tests to verify your changes?
Not required for this change

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
NA

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by davinash** [comment]
Thanks @kirklund , Yes Please you can merge this change.

**Comment by kirklund** [comment]
@davinash please rebase on develop to fix the new conflicts and I'll merge to develop. Thanks!

**Comment by davinash** [comment]
Hi @kirklund Updated the PR and running the tests now again. Please review and you can merge the same.

**Comment by kirklund** [comment]
Too many conflicts again. I keep trying to pull this in, but you've changed so many files that it's almost guaranteed to hit conflicts. I even tried to discard your changes in any files with conflicts but then when I rebased to combine your 3 commits into 1, it ended up with a few dozen conflicts. Sorry, I can't commit this without you resolving conflicts again. Please combine your commits into a single commit as well. Thanks, Kirk

**Comment by metatype** [comment]
I think the best way to proceed with this PR is to split the changes into smaller PR's that are easier to review and merge.

**Comment by PurelyApplied** [comment]
In the interest of clarity, I've gone ahead and rerun the removal of redundant modifiers and opened them across five PRs.

See #1358 #1359 #1360 #1361 #1362

**Pull request closed without merging**
