### PR TITLE
GEODE-6678: Remove singleton cache reference from ClusterManagementServiceProvider

### PR DESCRIPTION
**Pull request by jdeppe-pivotal**
Authored-by: Jens Deppe <jdeppe@pivotal.io>

Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [ ] Is your initial contribution a single, squashed commit?

- [ ] Does `gradlew build` run cleanly?

- [ ] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, check Concourse for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by jdeppe-pivotal** [comment]
A couple of comments about this PR which arose from feedback that we shouldn't be using a static accessor to a singleton `Cache` instance (`CacheFactory.getAnyInstance()` for example). Here are the highlights:
- Previously we had `ClusterManagementServiceFactory`s which had implementations in both `geode-management` and `geode-core`. These served as the (auto-magic) differentiators for the context that the user would call `ClusterManagementServiceProvider.getService()` in. Essentially these are replaced with `ClusterManagementServiceConfig` objects that a user has to explicitly configure and pass to `new ClientClusterManagementService(config)` to get an instance of `ClusterManagementService`. The auto-magicness is gone. The service loading shenanigans is also gone.
- The `ClusterManagementServiceConfig` objects are context dependent so a user does have to be aware of which impl they should be using.
- I applied a builder pattern to the creation of `ClusterManagementServiceConfig` objects. I think this is more flexible than constructors with a bunch of args (for which it isn't always clear which are required). In general, it's no problem adding an additional param to an existing builder pattern down the road. Also, builders are more flexible than setters as they are able to apply mutual exclusivity as part of API and not just at runtime.
- I think having a single entry point, into our API (now `new ClientClusterManagementService(config)`) is preferable to having separate classes. Could also do something like `JavaClientClusterManagementServiceProvider.getService(host, port)` and `GeodeClusterManagementServiceProvider.getService(cache)` but I think having the config object be the differentiator makes the API more discoverable.
- Lastly, retrieving the CMS on the locator is an outlier and is just `InternalLocator.getLocator().getClusterManagementService()`.

**Comment by jinmeiliao** [comment]
I like the builder pattern here, it is better than constructors with various params. Can we directly use the builder to build the service itself instead of building the interim config object? Here are the differences of these two apis:

What the PR uses:


```
// on server
    ClusterManagementServiceConfig config = GeodeClusterManagementServiceConfig.builder()
        .setCache(ClusterStartupRule.getCache())
        .setUserName()
        .setPassword()
        .build();
    ClusterManagementService service = new ClientClusterManagementService(config);

    // on geode client  -- can't set username/password first before setting the cache
    ClusterManagementServiceConfig config = GeodeClusterManagementServiceConfig.builder()
        .setClientCache(ClusterStartupRule.getClientCache())
        .setUsername()
        .setPassword()
        .build();
    ClusterManagementService service = new ClientClusterManagementService(config);


    // on java client
    ClusterManagementServiceConfig config = JavaClientClusterManagementServiceConfig.builder()
        .setHost("localhost")
        .setPort(locator.getHttpPort())
        .setUsername("test")
        .setPassword("test")
        .build();
    cmsClient = new ClientClusterManagementService(config);
 ```
  
Suggested API:

```
// on server
    ClusterManagementService service = new GeodeManagementServiceBuilder().setCache(cache).setUserName().setPassword().build();
    
    // on geode client
    ClusterManagementService service = new GeodeManagementServiceBuilder().setClientCache(cache).setUserName().setPassword().build();
    
    // on java client
     ClusterManagementService service = new JavaClientManagementServiceBuilder().setHost(host).setPort(port).setUsername().setPassword().build();```

**Comment by jdeppe-pivotal** [comment]
I don't mind the suggested approach, although I do feel that a single entry-point into our API is better - it then allows for easier discovering of what different config classes are available - either through reading the docs or through using the API in an IDE.

**Comment by jinmeiliao** [comment]
Then how about:
```
// on server
    ClusterManagementService service = ClusterManagementServiceBuilder.geodeClientBuilder().setCache(cache).setUserName().setPassword().build();
    
    // on geode client
    ClusterManagementService service = ClusterManagementServiceBuilder.geodeClientBuilder().setClientCache(cache).setUserName().setPassword().build();
    
    // on java client
     ClusterManagementService service =ClusterManagementServiceBuilder.javaClientBuilder().setHost(host).setPort(port).setUsername().setPassword().build();```

```

**Comment by jdeppe-pivotal** [comment]
@jinmeiliao Unfortunately, since the top-level API is independent of Geode code, we couldn't have `Cache` references here.

**Comment by jinmeiliao** [comment]
I still feel like having to create a config object first in order to create a client service is an extra burden for the user. Since this config object is the first thing user has to create, it still feels like a "different" entry point for me. I would rather use a different builder for simplicity.

**Pull request merged**
