### PR TITLE
GEODE-240: Remove deprecated methods on TransactionEvent

### PR DESCRIPTION
**Pull request by shankarh**
Removed deprecated methods getCreateEvents, getDestroyEvents, getPutEvents, getInvalidateEvents from the TransactionEvent.
Removed implementation for methods getCreateEvents, getDestroyEvents, getPutEvents, getInvalidateEvents from TxEvent and TxRmtEvent.
Added utility methods getCreateEvents, getDestroyEvents, getPutEvents, getInvalidateEvents in TxEventTestUtil.
Changed tests to use the new utilty methods from TxEventTestUtil.

Signed-off-by: Shankar <shankarh@apache.org>

Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?
Yes.  GEODE-240
- [x] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?
Yes.
- [x] Is your initial contribution a single, squashed commit?
Yes.
- [x] Does `gradlew build` run cleanly?
Yes.
- [x] Have you written or updated unit tests to verify your changes?
Yes.
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
Not applicable.
### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by ameybarve15** [comment]
+1 LGTM

**Comment by dschneider-pivotal** [comment]
This looks good

**Comment by davinash** [comment]
+1 LGTM

**Comment by shankarh** [comment]
Thanks @ameybarve15  @dschneider-pivotal @davinash for the review.

**Comment by shankarh** [comment]
Can this PR be merged?

**Pull request closed without merging**
