### PR TITLE
GEODE-4051 Add try catch to catch timeout exception

### PR DESCRIPTION
**Pull request by igorbarc**
GEODE-4051 Add try catch to catch timeout exception

Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [x] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [x] Is your initial contribution a single, squashed commit?

- [x] Does `gradlew build` run cleanly?

- [ ] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by nreich** [comment]
@igorbarc, some of the code in your submission is failing the automated code formatting tests (spotless) in Travis. Please run `gradlew spotlessApply` and push the resulting changes to pass those tests. The spotless formatting tests can be run locally as part of `gradlew build` or can be run separately using `gradlew spotlessCheck`

**Comment by igorbarc** [comment]
@nreich Thanks,  fixed, passed now

**Comment by igorbarc** [comment]
@kirklund Originally, issue reproduced with high load on jvms from client, while bouncing jvms. on system with some network issues between hosts, causing timeouts

To easily reproduce :
1) Add hardcoded throw of timeout exception in  waitForCurrentOperations
2) Start the grid,  with replication of buckets, assign buckets to one of the regions
3) Bounce one for the jvms.  

Result without fix : **Uncaught** exception processing  StateMarkerMessage   

org.apache.geode.GemFireIOException: Current operations did not distribute within 5008 milliseconds
        at org.apache.geode.distributed.internal.DistributionAdvisor.waitForCurrentOperations(DistributionAdvisor.java:833)
        at org.apache.geode.distributed.internal.DistributionAdvisor.waitForCurrentOperations(DistributionAdvisor.java:785)
        at org.apache.geode.internal.cache.StateFlushOperation$StateMarkerMessage.waitForCurrentOperations(StateFlushOperation.java:457)
        at org.apache.geode.internal.cache.StateFlushOperation$StateMarkerMessage.process(StateFlushOperation.java:362)
        at org.apache.geode.distributed.internal.DistributionMessage.scheduleAction(DistributionMessage.java:374)
        at org.apache.geode.distributed.internal.DistributionMessage$1.run(DistributionMessage.java:440)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.geode.distributed.internal.DistributionManager.runUntilShutdown(DistributionManager.java:662)
        at org.apache.geode.distributed.internal.DistributionManager$5$1.run(DistributionManager.java:958)
        at java.lang.Thread.run(Thread.java:748)

The flush marker  message will not be sent, and buckets without redundancy will not return to zero, even after re-balance 


Result with fix : in log 
)  **Exception caught** while determining channel state
org.apache.geode.GemFireIOException: Current operations did not distribute within 5048 milliseconds
        at org.apache.geode.distributed.internal.DistributionAdvisor.waitForCurrentOperations(DistributionAdvisor.java:833)
        at org.apache.geode.distributed.internal.DistributionAdvisor.waitForCurrentOperations(DistributionAdvisor.java:785)
        at org.apache.geode.internal.cache.StateFlushOperation$StateMarkerMessage.waitForCurrentOperations(StateFlushOperation.java:487)
        at org.apache.geode.internal.cache.StateFlushOperation$StateMarkerMessage.process(StateFlushOperation.java:362)
        at org.apache.geode.distributed.internal.DistributionMessage.scheduleAction(DistributionMessage.java:374)
        at org.apache.geode.distributed.internal.DistributionMessage$1.run(DistributionMessage.java:440)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.geode.distributed.internal.DistributionManager.runUntilShutdown(DistributionManager.java:662)
        at org.apache.geode.distributed.internal.DistributionManager$5$1.run(DistributionManager.java:958)
        at java.lang.Thread.run(Thread.java:748)

buckets without redundancy will return to zero after jvm start

**Comment by dschneider-pivotal** [comment]
igorbarc, thanks for this work. I'm going to close it and create a new pull request that includes a unit test.

**Pull request closed without merging**
