### PR TITLE
GEODE-6634: Fix parallel option for repeatTest

### PR DESCRIPTION
**Pull request by jdeppe-pivotal**
Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [ ] Is your initial contribution a single, squashed commit?

- [ ] Does `gradlew build` run cleanly?

- [ ] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, check Concourse for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by upthewaterspout** [comment]
Will this potentially make the jobs run with more parallelism than we can handle? I think we sized things so that dunitParallelForks=24 will fill up the machine. If two jobs run in parallel, we will get weird failures now due to overprovisioning?

The lack of forkEvery=1 was intentional to make sure people introduced tests that cleaned up after themselves. But we keep running into confusion over this, so maybe accepting the new normal that tests don't clean up state is fine.

**Comment by jdeppe-pivotal** [comment]
Currently, the jobs end up running with both `--parallel` and `--no-parallel` - just because of the way the scripts are written; I'm not sure which one gets precedence. With this change we can correctly select the option using the CI job parameters.

Perhaps the fix is elsewhere as I'm not quite sure exactly how `repeatTest` works. It shouldn't be spawning 1000's of JVMs though.

**Comment by jdeppe-pivotal** [comment]
Currently, the jobs end up running with both `--parallel` and `--no-parallel` - just because of the way the scripts are written; I'm not sure which one gets precedence. With this change we can correctly select the option using the CI job parameters.

Perhaps the fix is elsewhere as I'm not quite sure exactly how `repeatTest` works. It shouldn't be spawning 1000's of JVMs though.

**Comment by jdeppe-pivotal** [comment]
Hmmm, I think the test that I touched and triggered this change is really the culprit. I will investigate further...

**Comment by upthewaterspout** [comment]
Got it. I think we should make sure this job runs without parallel in the job parameters then - is that already the case or can you fix that as part of this change as well?

I'm ok with going to forkEvery=1, I just wanted to make sure you understood the history.

The last time I've seen gradle create 1000s of JVMs, it had something to do with the way gradle was scanning for matching tests (I created a new JVM for each potential test). So maybe something weird has happened or after some gradle upgrade we're back to scanning everything again.

**Comment by jdeppe-pivotal** [comment]
@upthewaterspout Are you OK with this as it is now?

**Pull request merged**
