### PR TITLE
GEODE-4902: Refactor LogMarker class and usage

### PR DESCRIPTION
**Pull request by PurelyApplied**
* Distinguish those markers at the TRACE and DEBUG levels (now Markers named *_VERBOSE) from those that log at a coarser granularity (now Markers named *_MARKER) to prevent accidental misuse.
* Suppress only *_VERBOSE markers by default, from previous behavior of suppressing all markers.
* Refactor some pathological log checks, e.g., change a log from debug to trace when it is gated behind ifTraceEnabled block.
* Remove unused Markers.
* Remove any log marker logic from AdminWaiters exception message generation.  Exceptions now always include a full message.
* Remove marker-gated print to System.out in PersistentOplogSet -- direct calls to System.out should not exist in that class.
* Add marker EVENT_ID_TO_STRING_VERBOSE to explicitly distinguish instance of marker used in logic not immediately consumed by a logger.  The consumption of EventId::toString should only exist at logging in any event.

* Remove nearby dead code and dead code detected during marker removal.
* Expand wildcard imports in touched files.
* Remove TODO comments, at least one of which was a decade old.
* Collapse nearby, redundant catch blocks
* Remove empty finally blocks
* Update documentation page to refer to GEODE_VERBOSE, from deprecated GEMFIRE_VERBOSE

Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [x] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [x] Is your initial contribution a single, squashed commit?

- [x] Does `gradlew build` run cleanly?

- [ ] Have you written or updated unit tests to verify your changes?

- [n/a] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by PurelyApplied** [comment]
Sorry for such a large diff -- these tags get everywhere, but I feel the renaming has value since this there are many places where it seems that logging is intended bug inadvertently suppressed.

Because this commit is, as the correction of a perceived bug, re-enabling many suppressed logging statements at coarse log levels, we may wish to make a note in the next release that logs may be more verbose than before.

**Comment by PurelyApplied** [comment]
@jdeppe-pivotal Maybe, but I think not?  The things to note:

* The vast majority of these markers are only applied at the TRACE level, and much of the remaining marker usage is at the DEBUG level.  It is unlikely that these usages would be considered common.
* The only marker documented is `GEMFIRE_VERBOSE` (changed in this commit to document `GEODE_VERBOSE`).
* This documentation concludes with "Typically, it’s more useful to simply enable DEBUG or TRACE on certain classes or packages instead of for the entire Geode product. However, this setting can be used for internal debugging purposes if all other debugging methods fail."  Explicitly, the intent is for internal debugging.
* Consequently, the marker definitions are themselves in an `internal` package, even tough they present a public profile.

I agree that it's a strange grey area.  But I also thing the root cause of this bug -- that non-debug level logs were being improperly suppressed -- was due to poor naming in these markers.

I suppose there's no inherent need for the marker's field name to match it's string name / the string used in the `log4j2.xml`.  I could try to coerce the old marker strings into the new marker lists.  But since several markers were split to distinguish `*_VERBOSE` debug level logging and `*_MARKER` coarser level logging, it might be awkward to map from the old to the new.  But I could give it a go, if you or anyone else feels strongly about it.

**Comment by PurelyApplied** [comment]
Precheckin green.

**Comment by jinmeiliao** [comment]
how much change do we have without renaming of the markers?

**Comment by PurelyApplied** [comment]
Not as much but still quite a bit.  Because of the non-descriptive naming, many of the tags were improperly used in INFO / WARNING / ERROR level log statements -- the core issue this bug ticket is addressing.  Each of these log statements require a new `LogMarker`.  (An alternative solution would be to remove these tags altogether, but the diff would be the same.)

Many log statements were pathologically locked, such as `if (debugIsEnabled) { logger.trace(...); }`.  These were corrected to check the log level in question.

Other minor improvements noted in the commit message.

**Pull request merged**
