### PR TITLE
GEODE-5800: remove redundant casts for `DataSerializer.readObject()`

### PR DESCRIPTION
**Pull request by galen-pivotal**
and remove unused methods on `InternalDataSerializer`.

### CODE REVIEW

**Comment by PurelyApplied** [comment]
+1 for code cleanup, obviously pending merge conflict resolution and failed test examination.  I'm not confident in how `AnalyzeSerializablesJUnitTest` desire to not break backwards compatibility works in practice.

It also looks like we've let this PR get stale enough that the test failures are a bit strange.  It looks like `StressNewTest` failures were `UnitTest` failures, but didn't fail in `Build`.  But `Build` has been replaced by a dedicated `UnitTest` job in these past three weeks.  Still, somewhat concerning that the stress went red where the `Build` didn't.

**Comment by pivotal-jbarrett** [comment]
@galen-pivotal What you waiting for to merge this change?

**Comment by galen-pivotal** [comment]
I was waiting on GEODE-6036 (#2997) before fixing sanctioned serializables. I haven't pushed that up yet but will in a minute.

**Comment by galen-pivotal** [comment]
I'm going to close this until I have more time to devote to cleaning up tests, etc. around this.

**Pull request closed without merging**
