### PR TITLE
GEODE-265: Removing deprecated API from Execution interface.

### PR DESCRIPTION
**Pull request by deepakddixit**
- Removed following deprecated API from Execution interface

1. public Execution<IN, OUT, AGG> withArgs(IN args)
2. public ResultCollector<?, ?> execute(String functionId, boolean hasResult)
      throws FunctionException
3. public ResultCollector<?, ?> execute(String functionId, boolean hasResult, boolean isHA)
      throws FunctionException;
4. public ResultCollector<?, ?> execute(String functionId, boolean hasResult, boolean isHA,
      boolean optimizeForWrite) throws FunctionException

- Removed implementation of these deprecated API's

- Fixed RollingUpgrade2DUnitTest.

### CODE REVIEW

**Comment by metatype** [comment]
Thanks for your contribution!

If I'm reading the log correctly, `withArgs(IN args)` was deprecated one month ago.  We should *not* remove this from the public API until the next major version (e.g. 2.0.0).  In the future when we deprecate an API it would be helpful to mark *when* it was deprecated to help track this more explicitly.  Can you remove this from the changeset?

```
commit aaef124e3d4d7b46c82ddb4d2af65ee48b73ba53
Author: Alyssa Kim <micro9110@gmail.com>
Date:   Sat Apr 15 17:48:00 2017 -0700

    GEODE-728: Rename Execution.withArgs to Execution.setArguments
    
     * created setArguments
     * deprecated withArgs
     * implemented setArguments of all Execution implementations in Geode project
     * replaced all of withArgs with setArguments
    
    This closes #457
```

**Comment by deepakddixit** [comment]
@metatype Thanks for review. I have removed withArgs related changes.

**Comment by jhuynh1** [comment]
I think these changes are ok (I didn't check when these were deprecated but I assume @metatype already did the grunt work on it.  I can merge these changes in if no one has any other reviews

**Comment by metatype** [comment]
@jhuynh1 I just noticed the one recent deprecation.  Given this is a public API change you should probably double-check me :-)

**Comment by jhuynh1** [comment]
@metatype Will do for both this and PR#511

**Pull request closed without merging**
