### PR TITLE
GEODE-9419: Handle IOExceptions when Radish clients disconnect

### PR DESCRIPTION
**Pull request by jdeppe-pivotal**
- This restores some of the behavior of GEODE-9411

Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [ ] Is your initial contribution a single, squashed commit?

- [ ] Does `gradlew build` run cleanly?

- [ ] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, check Concourse for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by DonalEvans** [comment]
Some small refactoring changes aside, this seems to just be a revert of GEODE-9411. Is there some middle ground solution that would prevent the spurious exception logging from Netty but preserve the behaviour where we don't close the connection if we hit any `IOException` at all, regardless of the origin?

**Comment by jdeppe-pivotal** [comment]
Since `IOException`s are checked, the implication is that they may be recoverable. However, in this case since netty is telling us about this problem, there isn't anything we can do about it. We're being told that the client is gone and we can perform any necessary cleanup.

**Comment by DonalEvans** [comment]
> Since `IOException`s are checked, the implication is that they may be recoverable. However, in this case since netty is telling us about this problem, there isn't anything we can do about it. We're being told that the client is gone and we can perform any necessary cleanup.

Aah, I see now. As long as we can be sure that we only see an `IOException` when the client is gone, and not in other cases, then it should be fine to just revert the entire commit for GEODE-9411. If we think there might be cases where an `IOException` is thrown and we don't want to close the connection, maybe we could check for the "Connection reset by peer" message in the exception and close if we see that?

**Comment by jdeppe-pivotal** [comment]
Closing in favor of a complete revert.

**Pull request closed without merging**
