### PR TITLE
UDA functionality for OQL engine of Geode

### PR DESCRIPTION
**Pull request by ahshahid**
Changes in querying engine to support UDA creation and querying . Using profile exchange as well as p2p messaging to transfer UDA information across peers. Added junit & dunit tests for the same.
I have not been able to run the precheckin target as on my laptop it took inordinate amount of time & still did not complete . At that time it had run some 6000 + tests.

### CODE REVIEW

**Comment by ahshahid** [comment]
The check test failed because of new element uda-manager in xsd. I will modify the test to expect uda-manager

**Comment by upthewaterspout** [comment]
Thanks for sending this code Asif!

I ran a precheckin, and there are some failing tests.
*    ResourceManagerDUnitTest. testRemoveDuringQuery
*    BugJUnitTest. testBug32251
*    RegionJUnitTest. testQueryServiceInterface
*    RegionJUnitTest. testShortcutMethods
*    UDAPartitionedQueryDUnitTest. testUDANoGroupBy
*    UDAPartitionedQueryDUnitTest. testUDAWithGroupBy
*    IndexCreationJUnitTest. testIndexCreation
*    QueryFromClauseCanonicalizationJUnitTest. testCanonicalizedFromClause
*    CompactRangeIndexJUnitTest. testUpdateInProgressWithMethodInvocationInIndexClauseShouldNotThrowException
*    AnalyzeSerializablesJUnitTest. testDataSerializables
*    AnalyzeSerializablesJUnitTest. testSerializables

I think the next steps on this are to send the proposal with the description of the changes to the mailing list and work on reviewing these changes and fixing the failures.

Proposal:
https://cwiki.apache.org/confluence/display/GEODE/OQL+Aggregate+functions+and+UDA

**Comment by ahshahid** [comment]
Thanks Dan.
I will look at the failures by tomorrow & propose a fix.
I will also update the wiki with the changes description.
Regards
Asif

**Comment by upthewaterspout** [comment]
I put this pull request on the feature branch feature/GEODE-1269 so we can work on it together to fix some of these failures.

**Comment by upthewaterspout** [comment]
I also created a JIRA for these changes - feel free to update: 
https://issues.apache.org/jira/browse/GEODE-1269

**Pull request closed without merging**
