### PR TITLE
Feature/geode 5530 assembly

### PR DESCRIPTION
**Pull request by rhoughton-pivot**
Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [ ] Is your initial contribution a single, squashed commit?

- [x] Does `gradlew build` run cleanly?

- [x] Have you written or updated unit tests to verify your changes?

- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by metatype** [comment]
What are all the new *-test modules for?  I also don't understand creating empty test classes that just extend a base class.

**Comment by pivotal-jbarrett** [comment]
Some people seem to like extending test cases and when that is done across modules or test types then the base class must be shared. A base class is extracted and moved to the test module and a test class is created to extend it and run from the Test sources. 

The other opinion is to stop this practice of extending Test classes.

**Comment by metatype** [comment]
So if the idea is that extracting shared test utilities, fixtures, etc into a `*-test` submodule is necessary  because that's the best way to integrate with IntelliJ then sure let's do it (even though the additional complexity is annoying).  

I suggest sharing this idea on `dev@geode` so everyone is aware of this pattern and uses the test submodules correctly.

I think you should take the extra step to review and correctly factor any extended test classes.  I'm not in favor of creating artificial, empty subclasses.

Example:  perhaps the right choice for `ExportLogsDUnitTest` is to move `geode-web/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/ExportLogsOverHttpDistributedTest.java` into geode-core until we can properly break out gfsh and geode-web.

Another example:  `extensions/geode-modules-test/src/main/java/org/apache/geode/modules/session/TestSessionsBase.java` is only used by classes in `extensions/geode-modules-tomcat7/src/integrationTest/java/org/apache/geode/modules/session/Tomcat7SessionsJUnitTest.java`.  Why move that?  Seems like it belongs next to it's subclasses since it isn't shared.

**Comment by pivotal-jbarrett** [comment]
There are a dozen ways to skin this cat and we are 90% complete with this way. Anyone is welcome to refactor further if they think there is a better approach. This approach takes the path of least resistance to correct a wrong.

Once complete there won't be any inter or intra project test source dependencies so the pattern will become painfully obvious. The pattern was also discussed in a thread between Kirk and I last week.

Please refactor any tests you don't like and if you can delete the shared test project in the processes even better.

`ExportLogsOverHttpDistributedTest.java` can't be in `geode-core` because it has build and runtime dependencies that `geode-core` does not and should not have.

`TestSessionsBase.java` is used by both tomcat 6 and tomcat 7 modules.

**Comment by pivotal-jbarrett** [comment]
If it makes you feel any better. I just tested and a default import of the project into IJ works. No more disabling the module per source set.

**Comment by metatype** [comment]
You're right, I chose poor examples.

I agree with the approach in general.  I'm still unabashedly sad to see new empty test subclasses.

**Comment by pivotal-jbarrett** [comment]
Me too. Next story will make you less sad.

**Pull request merged**
