### PR TITLE
GEODE-2660 Add @Experimental to the Redis adapter.

### PR DESCRIPTION
**Pull request by galen-pivotal**

### CODE REVIEW

**Comment by galen-pivotal** [comment]
@hiteshk25 @kirklund @upthewaterspout @bschuchardt

**Comment by galen-pivotal** [comment]
I can't merge as I'm not a committer; would someone else be so kind, assuming these changes look good?

**Comment by upthewaterspout** [comment]
I think adding @Experimental the the internal classes might be overkill, @Experimental really just has meaning for the public API.

**Comment by galen-pivotal** [comment]
@upthewaterspout okay, you'd just put it on GeodeRedisServer?

**Comment by upthewaterspout** [comment]
@galen-pivotal - it looks like the public API is just GeodeRedisServer.

**Comment by galen-pivotal** [comment]
@bschuchardt want to merge this?

**Comment by bschuchardt** [comment]
I don't think we can merge these changes until the lock-service variables in ExeuctionHandlerContext are made static.  As it's currently implemented every ExecutionContextHandler has its own lock service, so concurrent operations aren't protected.  This also calls into question any performance figures obtained with this code since it isn't functioning properly.

**Comment by bschuchardt** [comment]
Also, since we're talking about releasing v 1.2 soon it would be nice to add the Experimental annotation with this same commit since it is breaking compatibility with v 1.1.

**Comment by galen-pivotal** [comment]
@bschuchardt This is just the experimental annotation, not changes.

**Comment by bschuchardt** [comment]
my bad - I checkout out ggreen's branch by mistake.  I don't see any @Experimental at all in your branch.  It looks like your second commit removed it from GeodeRedisServer.java when you meant to only remove it from the other classes.

**Comment by galen-pivotal** [comment]
@bschuchardt Check it out again; I force-pushed with just the annotation on GeodeRedisServer.

**Comment by bschuchardt** [comment]
got it

**Pull request merged**
