### PR TITLE
Fix the Native Client Build on Ubuntu

### PR DESCRIPTION
**Pull request by davinash**
verified on Ubuntu and centos

Change is 

```
 ~/source/open/geode/build (next-gen-native-client-software-grant) $ git diff
diff --git a/src/cppcache/src/CMakeLists.txt b/src/cppcache/src/CMakeLists.txt
index 04c51a0..35b3799 100644
--- a/src/cppcache/src/CMakeLists.txt
+++ b/src/cppcache/src/CMakeLists.txt
@@ -78,11 +78,7 @@ if(CMAKE_SYSTEM_NAME STREQUAL "SunOS")
     set(SOURCES ${SOURCES} $<TARGET_OBJECTS:gfcppasm>)
   endif()
 endif()
-if (${UNIX})
-  target_link_libraries(_gfcppcache INTERFACE
-      z
-  )
-elseif (${WIN32})
+if (${WIN32})
   target_link_libraries(_gfcppcache INTERFACE
       Dbghelp
   )
@@ -91,6 +87,7 @@ endif()
 target_link_libraries(_gfcppcache INTERFACE
   ACE
   libxml2
+  z
 )
 target_compile_definitions(_gfcppcache INTERFACE
     # TODO replace BUILD_CPPCACHE with built-in _DLL

```

I am not sure why 	bc7fa36 is showing in the PR.

### CODE REVIEW

**Comment by PivotalSarge** [comment]
Elegant. Looks good to me.

**Comment by pivotal-jbarrett** [comment]
I've been down this ordering road before. Pretty sure this change will break on Windows and possibly Solaris. If the known to work platforms in the BUILDING doc, which have you tested this pull against?

**Comment by davinash** [comment]
@pivotal-jbarrett  Yes you are correct, previous change will break windows. I have updated PR. Tested on ubuntu and CentOS.

**Comment by upthewaterspout** [comment]
This PR fixed the issue for me on ubuntu.

**Comment by pivotal-jbarrett** [comment]
Looking at this a little more... I don't think that gfppcache directly depends on -lz. If it is just a transitive dependency from libxml2 then we should move the -lz to target library definition for libxml2 and remove it from here. @davinash are you interested in taking a stab at that?

**Comment by davinash** [comment]
Thanks @pivotal-jbarrett , I have handled review comments, tested on Ubuntu and CentOS.

**Comment by metatype** [comment]
Any further discussion?

**Comment by pivotal-jbarrett** [comment]
@metatype looks good if you want to merge it.

**Comment by davinash** [comment]
@pivotal-jbarrett @metatype I have merged the change. 
https://git-wip-us.apache.org/repos/asf?p=geode.git;h=e92cb63

Closing this PR now.

**Pull request closed without merging**
