### PR TITLE
GEODE-2506 Update Spring from 4.3.2 to 4.3.6

### PR DESCRIPTION
**Pull request by metatype**
Update Spring framework version.  Also implement a version override
strategy for transitive dependencies.  This ensures that versions
specified in gradle/dependency-versions.properties are honored.
Useful when a newer version of a transitive dependency is needed
but we'd prefer not to declare a first class dependency.

This change affects commons-beanutils which used 1.8.3 from
shiro-core but we specify 1.9.3.

### CODE REVIEW

**Comment by metatype** [comment]
@upthewaterspout @scmbuildguy

**Comment by jaredjstewart** [comment]
Can you explain why the version override strategy is necessary?  I think geode-pulse (or any other submodule with an explicit dependency on commons-beantuils) should end up with version 1.9.3 already without any change to `dependency-resolution.gradle`, since the version you've specified (1.9.3) is higher than the one coming in transitively (1.8.3).

**Comment by metatype** [comment]
In this case geode-pulse uses commons-beanutils v1.9.3 while geode-core is pulling in commons-beanutils v1.8.3 via shiro-core.  The version is different between `lib/*` and `geode-pulse-*.war`.

The override resolution strategy gives us another way to control transitive dependencies.  In some (rare) instances, we may want to ship a different version than specified in the pom file.  Let me know if you think this is getting overly complicated.

**Comment by jaredjstewart** [comment]
It seems like it might be simpler to add an explicit dependency for commons-beanutils to geode-core.  That way if we later introduce some new dependency which requires say commons-beanutils 1.10.1, there will be no need to troubleshoot since dependency resolution will still work as expected.

**Comment by kirklund** [comment]
I think I should pull this in before applying https://reviews.apache.org/r/56934/. My changes for GEODE-2460 are missing the webapp NOTICE changes and the change to gradle/dependency-resolution.gradle.

**Pull request closed without merging**
