### PR TITLE
GEODE-9173: bump swagger2 to 3.0.0

### PR DESCRIPTION
**Pull request by mkevo**
Springfox [README.md:](https://github.com/springfox/springfox/blob/3.0.0/README.md#migrating-from-existing-2x-version)

Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [x] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [x] Is your initial contribution a single, squashed commit?

- [x] Does `gradlew build` run cleanly?

- [ ] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, check Concourse for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by onichols-pivotal** [comment]
I've tried this once before and gave up.  Perhaps you'll have better luck.

**Comment by kohlmu-pivotal** [comment]
Yeah, it's not that simple to just change version numbers... They have made some changes internally that you need to address.. some extra code and initialization classes...

**Comment by mkevo** [comment]
I will try to investigate, and probably find a fix for this.

**Comment by kohlmu-pivotal** [comment]
Thanks @mkevo.

**Review by rhoughton-pivot — APPROVED** [review]

**Comment by kohlmu-pivotal** [comment]
@mkevo the simplest test to confirm that this works, you'll have to hit the swagger docs URL once deployed. I think, when I attempted this the first time (before creating this ticket), it didn't just work by removing the annotation.

This simple test to confirm that the Swagger docs URL works will be a faster test than running the PR pipeline.

**Comment by onichols-pivotal** [comment]
If this upgrade changes the swagger output format at all, also be sure to update geode-management/src/test/script/update-management-wiki.sh to handle the new format

**Comment by mkevo** [comment]
I spent some time uplifting this dependency, but without a success.
First of all, I tried to follow steps from [README.md](https://github.com/springfox/springfox/blob/3.0.0/README.md#migrating-from-existing-2x-version). This is not working for us.
Then I tried to do more changes:

-  in SwaggerConfig by replacing @EnableSwagger2 with EnableSwagger2WebMvc
-  replace Swagger Docs URL(/swagger-ui.html) with /swagger-ui/index.html
-  follow steps from https://www.baeldung.com/swagger-2-documentation-for-spring-rest-api
-  try two steps uplift, first to 2.10.x, then to 3.0.0, without success

I will close this PR, as I'm not able to uplift it. Hope that someone else will have a bit of more luck.

**Pull request closed without merging**
