### PR TITLE
GEODE-5536 force unitTest compilation to be dependency of source classes

### PR DESCRIPTION
**Pull request by rhoughton-pivot**
Co-authored-by: Robert Houghton <rhoughton@pivotal.io>
Co-authored-by: Dick Cavender <dcavender@pivotal.io>

Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [x] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [x] Is your initial contribution a single, squashed commit?

- [x] Does `gradlew build` run cleanly?

- [x] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by rhoughton-pivot** [comment]
@upthewaterspout @pivotal-jbarrett Here is the dependency change for unit-test compilation

**Comment by upthewaterspout** [comment]
If this is really just to make devBuild work, we should make the devBuild depend on these things, not classes.

The classes target is supposed to compile the production source. It's weird to have production source compilation depend on test source compilation.

**Comment by rhoughton-pivot** [comment]
@upthewaterspout Perhaps it is odd to have `classes` depend on test sources, but we already do this for all of the acceptance/ui/integration/distributed/upgrade/performance test sources. I'm literally making them all behave the same.

**Comment by pivotal-jbarrett** [comment]
@upthewaterspout this is for `build` too, not just `devBuild`. Gradle doesn't build `testClasses` unless you do a `check`, which by default `build` does. It doesn't not build `*TestClasses` until you explicitly invoke `*Test` task. This would result in builds that didn't attempt to compile tests and potentially missing compilation failures as a result. The goal of these changes and dependencies it to assure that all "builds" invoke `compile*TestJava`.

**Comment by metatype** [comment]
It looks to me like a source set defined by the Facet plugin automatically gets added as a dependency of `build`.  Can you check that?  If so, I don't these adding any of the `compile*TestJava` tasks as a dependency of `classes` is necessary and just adds complexity.

I would keep the dependencies of the `devBuild` task completely separate.

**Comment by rhoughton-pivot** [comment]
It's not just about devBuild. We (Jake and I) disagree with Gradle that
'assemble' or 'compile' should not compile the test Java code, our change
ensures that all test sources are compiled as part of any life cycle task
that performs compilation

**Comment by upthewaterspout** [comment]
How about making each subprojects' assemble task depends on these compile tasks then?

That would also make sure that things like 'Geode-core:build' will compile the integration test source.

Anyway,  I'm ok with merging this because it's not making things worse,  but I think since we noticed this problem this might be a good time to clean it up.

**Comment by metatype** [comment]
I think hooking to `testClasses` would be consistent with the typical Java lifecycle.  Why do we want to deviate from that?

As I said before, the Facets plugin already adds new source sets to `build` so the test classes *do* get compiled.  Check out this dry run with the explicit dependencies removed:

```
› gradle -m :geode-core:build -x test | grep compile | grep Test
:geode-core:compileAcceptanceTestJava SKIPPED
:geode-core:compileTestJava SKIPPED
:geode-core:compileIntegrationTestJava SKIPPED
:geode-core:compileDistributedTestJava SKIPPED
:geode-core:compilePerformanceTestJava SKIPPED
:geode-core:compileUiTestJava SKIPPED
:geode-core:compileUpgradeTestJava SKIPPED
```

I'm asking "why" because I want to have a simple, default build with no unnecessary customization.

My vote:  -0

**Comment by rhoughton-pivot** [comment]
Facets adds them to `build` but `build` in Gradle means to do EVERYTHING, including running the tests. So its not a 'simple' build line if you end up turning off tasks you don't like.

We deviate so that `assemble`, which means to compile my code, will compile the test sources, which are also code.

**Comment by metatype** [comment]
But why not hook `testClasses` into `assemble` then?  How far down the path of "fixing" the gradle lifecycle do you want to go :-)

**Comment by pivotal-jbarrett** [comment]
Fine, let's hook the xTest targets into testClasses and don't try to patch up gradle's oddities. Then add testClasses to devBuild.

**Comment by PurelyApplied** [comment]
The one failure appears to be unrelated.  Note the same failure in #2332 nearby precheckin run [[link](https://concourse.apachegeode-ci.info/teams/main/pipelines/pr-develop/jobs/DistributedTest/builds/649)].

**Comment by metatype** [comment]
Hey why was this merged?  The latest comments from @pivotal-jbarrett (and me) ask for changes to use `testClasses` as the hook.

@PurelyApplied

**Pull request merged**
