### PR TITLE
GEODE-2587: Refactored the OrderByComparator's compare method

### PR DESCRIPTION
**Pull request by nabarunnag**
Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [x] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [x] Is your initial contribution a single, squashed commit?

- [x] Does `gradlew build` run cleanly?

- [ ] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by nabarunnag** [comment]
Potential Reviewers
@ladyVader @jhuynh1 @boglesby @upthewaterspout @gesterzhou

**Comment by nabarunnag** [comment]
@ladyVader I am assuming that there should be tests already present testing the functional aspect. One of the tests did fail and caught an issue in my fix.
@jhuynh1 what do you think?

**Comment by jhuynh1** [comment]
We definitely have order by in the tests, whether or not they are adequate I am not sure.  doing a find on "order by" will show a log of queries in the tests...
The changes look good to me, if in the future we could collapse common code or extract some into smaller methods that would be great.

**Comment by nabarunnag** [comment]
Yes, we are opening a new ticket for eliminating the repeated code.
Analyzing the testcode for ORDER BY queries.

**Pull request closed without merging**
