### PR TITLE
GEODE-4622 Update library dependencies

### PR DESCRIPTION
**Pull request by metatype**
Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [X] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [X] Is your initial contribution a single, squashed commit?

- [X] Does `gradlew build` run cleanly?

- [ ] Have you written or updated unit tests to verify your changes?

- [X] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by metatype** [comment]
Testing notes:

- log4j 2.10.0 seems to break servlet session replication tests.
- fast-classpath-scanner gives different results than previously.
- shiro-core now depends on other shiro libraries (all ASL 2.0).
- swagger adds these libs:
   - byte-buddy (ASL)
   - javassist (MPL / LGPL / ASL)
   - reflections (WTFPL // approved by ASF)

**Comment by metatype** [comment]
clean precheckin

**Comment by jdeppe-pivotal** [comment]
To be clear, you're not intending to update log4j and fast-classpath-scanner now?

**Comment by metatype** [comment]
Correct.  log4j2 2.10.0 has a problem with Tomcat which shows up in our session replication tests.  

The new version of fast-classpath-scanner has different behavior which means we'll need to change our usage if we want to update.

**Comment by jdeppe-pivotal** [comment]
I'm actually about to update `fast-classpath-scanner` for another issue.

**Pull request merged**
