### PR TITLE
GEODE-7864: Always use curly braces for control flow statements

### PR DESCRIPTION
**Pull request by DonalEvans**
As stated in the [Geode Code Style Guide](https://cwiki.apache.org/confluence/display/GEODE/Code+Style+Guide), all control statements should have curly braces. This PR uses IntelliJ's "Run inspection By Name..." feature to identify and fix all instances in the codebase where this convention is not currently followed (some 3300+ instances) in order to make the code more consistent.

Authored-by: Donal Evans <doevans@vmware.com>

Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [ ] Is your initial contribution a single, squashed commit?

- [ ] Does `gradlew build` run cleanly?

- [ ] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, check Concourse for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by onichols-pivotal** [comment]
is it possible to update spotless rules to require/enforce use of curly braces going forward?

**Comment by DonalEvans** [comment]
> is it possible to update spotless rules to require/enforce use of curly braces going forward?

I think it should be possible to check, although I'm not too familiar with how spotless works. It's certainly possible to construct a regex that identifies control flow statements without curly braces, but ensuring there are no false positives might be tricky.

**Comment by onichols-pivotal** [comment]
would you plan to apply this on support branches as well?  yes might make it easier to backport fixes to support branches

**Comment by DonalEvans** [comment]
> would you plan to apply this on support branches as well? yes might make it easier to backport fixes to support branches

Ah, good call. Yeah, it should be trivial to apply to support branches too.

**Review by kirklund — APPROVED** [review]
Thanks for making these changes! Curly braces have been required by every one of our code styles since the code base started.

**Review by kohlmu-pivotal — APPROVED** [review]
lgtm

**Review by jdeppe-pivotal — APPROVED** [review]
Nice!

**Review by upthewaterspout — APPROVED** [review]
My codeowner files look fine.

It would be nice to have this sort of thing enforced/applied by spotless.

**Comment by DonalEvans** [comment]
For clarity, the failures in distributed-test-openjdk8 are GEODE-9038 and GEODE-5304, and the failure in acceptance-test-openjdk11 is GEODE-9252. All of these are known issues/flaky tests and not related to the changes in this PR.

**Review by Bill — APPROVED** [review]
I approve of @DonalEvans running the IJ inspection to add these braces. I have 83 code owner files and visually checking all of those doesn't make sense—so I did not. I am relying, in this case, on the compiler, the regression tests, and @DonalEvans's integrity to ensure no behavioral changes have sneaked in.

**Review by nabarunnag — APPROVED** [review]
LGTM.

**Comment by DonalEvans** [comment]
Force pushed after resolving merge conflicts

**Review by gesterzhou — APPROVED** [review]

**Review by jinmeiliao — APPROVED** [review]

**Pull request merged**
