### PR TITLE
GEODE-1995: Removed ReliableMessageQueue, ReliableMessageQueueFactory…

### PR DESCRIPTION
**Pull request by davinash**
…, ReliableMessageQueueFactoryImpl and

it's usage in the code from GemfireCacheImpl and DistributedRegion.

CC @dschneider-pivotal

### CODE REVIEW

**Comment by davinash** [comment]
Please review this PR, Thanks.

**Comment by dschneider-pivotal** [comment]
I think you should continue to remove code that was only used by ReliableMessageQueueFactoryImpl. This included the following:
1. LocalizedStrings that this class used.
2. ReliableDistributionData: the methods on this interface were only called by ReliableMessageQueueFactoryImpl. So this interface should be removed and all the implementations of this interface (lots of *Message classes).
3. DistributedRegion.sendQueue method: it is only called by ReliableMessageQueueFactoryImpl.
Getting rid of that method lets you delete SendQueueOperation which gets rid of SendQueueMessage which lets you get rid of SEND_QUEUE_MESSAGE (you will need to also remove some references for this message from DSFIDFactory).

It would be best to remove all this stuff with one checkin. Just just look over each class you remove and see what it references that will no longer be used.

**Comment by davinash** [comment]
Thanks @dschneider-pivotal  for review, I will make these changes.

**Comment by davinash** [comment]
All test passed. Please review.

**Comment by davinash** [comment]
Is this PR looking good now ?

**Comment by davinash** [comment]
@metatype , @dschneider-pivotal Please let me know if this is good to merge.

**Pull request closed without merging**
