### PR TITLE
GEODE-7463: make docLinks public

### PR DESCRIPTION
**Pull request by jmelchio**
- Provide structure for doclinks for better Swagger experience

Authored-by: Joris Melchior <joris.melchior@gmail.com>

Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [ ] Is your initial contribution a single, squashed commit?

- [ ] Does `gradlew build` run cleanly?

- [ ] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, check Concourse for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by jmelchio** [comment]
@onichols-pivotal @jinmeiliao @dschneider-pivotal @demery-pivotal

**Comment by jmelchio** [comment]
> 👍
> Are `GET /management/` and `GET /management` equivalent?

Yes, they are treated the same

**Comment by onichols-pivotal** [comment]
> > 👍
> > Are `GET /management/` and `GET /management` equivalent?
> 
> Yes, they are treated the same

Please add tests for both forms, and both with and without security enabled.

When I tried a quick curl tests, they do not appear equivalent to me:
$ curl -s http://localhost:7070/management/
{"latest":"http://localhost:7070/management/v1/api-docs","supported":["http://localhost:7070/management/v1/api-docs"]}

$ curl -s http://localhost:7070/management
(no output)

**Comment by jmelchio** [comment]
> > > +1
> > > Are `GET /management/` and `GET /management` equivalent?
> > 
> > 
> > Yes, they are treated the same
> 
> Please add tests for both forms, and both with and without security enabled.
> 
> When I tried a quick curl tests, they do not appear equivalent to me:
> $ curl -s http://localhost:7070/management/
> {"latest":"[http://localhost:7070/management/v1/api-docs","supported":["http://localhost:7070/management/v1/api-docs"]}](http://localhost:7070/management/v1/api-docs%22,%22supported%22:%5B%22http://localhost:7070/management/v1/api-docs%22%5D%7D)
> 
> $ curl -s http://localhost:7070/management
> (no output)

I tried in the browser and there they behave the same. I'll experiment and will add tests accordingly.

**Pull request merged**
