### PR TITLE
GEODE-2975: Change the location of the lucene xsd

### PR DESCRIPTION
**Pull request by upthewaterspout**
The lucene xsd was not in the right location on disk, which resulted in
a failure to validate lucene elements in the xml file.

Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [X] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [X] Is your initial contribution a single, squashed commit?

- [X] Does `gradlew build` run cleanly?

- [X] Have you written or updated unit tests to verify your changes?

- [X] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by upthewaterspout** [comment]
@nabarunnag @boglesby

**Comment by metatype** [comment]
Does this also affect the xsd location on http://geode.apache.org?

**Comment by upthewaterspout** [comment]
@metatype - Yes, we'll need to update the website as well, the location of the xsd is also wrong on the website, but for different reasons.

**Comment by boglesby** [comment]
This looks good for these xmls:
```
<lucene:fieldxx name="Agency"/>
```
```
<lucene:field namexx="Agency"/>
```
it still throws a ClassCastException for this, though:
```
<lucene:indexxx name="index">
```
I'm not sure if thats a problem or if its ok.

**Comment by upthewaterspout** [comment]
@boglesby - I see the problem with lucene:indexxx. It looks like in cache-1.0.xsd, which specify this in order to allow other schemas (like lucene.xsd) to extend region with additional elements:

`
      <xsd:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
`

Unfortunately, using 'lax' instead of 'strict' here means that we don't validate the new xsd as strictly - additional elements are ignored, etc.

I'm worried about the impact of changing this validation. I think the thing to do maybe is just to give a little better error message in our java code and call it a day.

**Comment by upthewaterspout** [comment]
@boglesby - Let me know what you think of the new changes. I added some validation to the code.

**Pull request closed without merging**
