### PR TITLE
GEODE-9759: replaces double-hyphens with &#8209;&#8209;

### PR DESCRIPTION
**Pull request by animatedmax**
In User Guide:
For code or flag prefixes, replaces "--" and "\-\-" and "\\-\\-" with "&#8209;&#8209;"
For non-prefix usage, replaces double-hyphens with colon or other appropriate punctuation.

### CODE REVIEW

**Review by davebarnes97 — CHANGES_REQUESTED** [review]
Awesome job, Max; the scope of this story was huge.
Everything looks great, with only a few exceptions. These are cases where the hyphen pair was not meant to be a command prefix, but was meant as an en-dash, for example, in geode-docs/managing/management/management_system_overview.html.md.erb, `"A JMX Manager node is a member that can manage other <%=vars.product_name%> members -- that is, other managed nodes -- as well as itself."`
I'll list the files where I found these occurrences. In most cases, the correct rendering would be an em-dash with no surrounding spaces. But if you choose to go with the widely-employed sequence of "space en-dash space", I won't complain. Most of us use it, so it's well understood, if not strictly correct.
So, I'd like to request changes to the following files that fit this case:

- managing/management/management_system_overview.html.md.erb
- managing/network_partitioning/how_network_partitioning_management_works.html.md.erb
- managing/troubleshooting/recovering_from_p2p_crashes.html.md.erb
- reference/topics/glossary.html.md.erb
Thanks!

**Comment by animatedmax** [comment]
@davebarnes97 As requested, I have reverted the changes that erroneously replaced the mdashes. Thanks for catching that!

**Comment by onichols-pivotal** [comment]
`--` could also be changed to &#8211; or &ndash; if desired (or &#8212; or &mdash; depending on the context)

**Review by davebarnes97 — APPROVED** [review]
I added one quick edit to the Architecture and Components page.
Approved.

**Pull request merged**
