### PR TITLE
 GEODE-5530: Removes test dependency from other test source sets

### PR DESCRIPTION
**Pull request by pivotal-jbarrett**
Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [x] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [x] Does `gradlew build` run cleanly?

- [x] Have you written or updated unit tests to verify your changes?

- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by pivotal-jbarrett** [comment]
Only failure was flaky

**Comment by PurelyApplied** [comment]
I can't seem to get IntelliJ to recognize the `distributedTestCompile` directive changes, making all of my tests full of unresolved references.  Were there any tricks you could recommend less extreme going nuclear on the project?

**Comment by pivotal-jbarrett** [comment]
@PurelyApplied I did nothing special other than reload the Gradle config and build.

**Comment by pivotal-jbarrett** [comment]
Anyone who tries this needs to make sure they have a recent IJ. Preferably something 2018 based.

**Comment by kirklund** [comment]
I've checked out the branch and I'm reviewing with testing it out. Thanks!

**Comment by kirklund** [comment]
Why does this change (rename) so many files but when I look at them they don't appear to be changed?

**Comment by kirklund** [comment]
So far I'm getting errors just trying to build on the command-line. I'll keep looking:
```
> Task :geode-dunit:javadoc
/Users/klund/dev/gemfire/open/geode-dunit/src/main/java/org/apache/geode/security/templates/SimpleAccessController.java:32: warning - Tag @link: reference not found: org.apache.geode.examples.SimpleSecurityManager
/Users/klund/dev/gemfire/open/geode-dunit/src/main/java/org/apache/geode/security/templates/SimpleAuthenticator.java:34: warning - Tag @link: reference not found: org.apache.geode.examples.SimpleSecurityManager
/Users/klund/dev/gemfire/open/geode-dunit/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientServerMiscDUnitTestBase.java:193: warning - Tag @see: reference not found: MessageJUnitTest#messageWillTimeoutDuringRecvOnInactiveSocket
/Users/klund/dev/gemfire/open/geode-dunit/src/main/java/org/apache/geode/test/junit/rules/GfshCommandRule.java:73: warning - Tag @link: reference not found: org.apache.geode.management.internal.cli.NetstatDUnitTest
/Users/klund/dev/gemfire/open/geode-dunit/src/main/java/org/apache/geode/security/templates/SimpleAccessController.java:32: warning - Tag @link: reference not found: org.apache.geode.examples.SimpleSecurityManager
/Users/klund/dev/gemfire/open/geode-dunit/src/main/java/org/apache/geode/security/templates/SimpleAuthenticator.java:34: warning - Tag @link: reference not found: org.apache.geode.examples.SimpleSecurityManager
/Users/klund/dev/gemfire/open/geode-dunit/src/main/java/org/apache/geode/security/templates/SimpleAccessController.java:32: warning - Tag @link: reference not found: org.apache.geode.examples.SimpleSecurityManager
/Users/klund/dev/gemfire/open/geode-dunit/src/main/java/org/apache/geode/security/templates/SimpleAuthenticator.java:34: warning - Tag @link: reference not found: org.apache.geode.examples.SimpleSecurityManager
8 warnings

> Task :geode-junit:javadoc
/Users/klund/dev/gemfire/open/geode-junit/src/main/java/org/apache/geode/internal/cache/TestObjectWithIdentifier.java:35: warning - Tag @link: reference not found: PartitionedRegionLocalMaxMemoryDUnitTest
/Users/klund/dev/gemfire/open/geode-junit/src/main/java/org/apache/geode/internal/cache/extension/mock/MockCacheExtension.java:34: warning - Tag @link: reference not found: org.apache.geode.cache30.CacheXml81DUnitTest
2 warnings

> Task :geode-connectors:compileTestJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :geode-rebalancer:compileTestJava
Note: /Users/klund/dev/gemfire/open/geode-rebalancer/src/test/java/org/apache/geode/cache/util/AutoBalancerJUnitTest.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :combineReports
All test reports at /Users/klund/dev/gemfire/closed/build/reports/combined

FAILURE: Build failed with an exception.

* Where:
Script '/Users/klund/dev/gemfire/open/gradle/spotless.gradle' line: 42

* What went wrong:
Execution failed for task ':gemfire-test:spotlessJava'.
> Do not use wildcard imports.  'spotlessApply' cannot resolve this issue.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 7m 57s
387 actionable tasks: 356 executed, 15 from cache, 16 up-to-date
```

**Comment by pivotal-jbarrett** [comment]
@kirklund GitHub UI calls them renames but they are really moves. All those files get moved to new homes but otherwise remain unchanged.

**Comment by pivotal-amurmann** [comment]
Worked for me as well. I initially ran into some `cannot find symbol` errors in IntelliJ 2018.2, but those got resolved once I followed your recommendations on the dev list last month to disable  "Create separate module per source set" and enable auto import.  I updated the wiki page to reflect these new setup requirements. Thoughts on adding this to the readme as well?

**Pull request merged**
