### PR TITLE
GEODE-8801: Update and review properties list

### PR DESCRIPTION
**Pull request by alb3rtobr**
Ticket GEODE-8801 description says:

> The file org/apache/geode/internal/cache/properties.html contains a list of several System properties that are used by Geode, as well as their default values. This list is for developer reference and is not referred to in any user-facing documentation, but is possibly incomplete and has not been maintained for some time.
>
> 1. Any properties referred to in the file that are no longer used should be removed
> 2. Any default values in the file that do not match the actual default should be updated
> 3. The "Public" field for each property is no longer meaningful and can be removed
> 4. Any System properties that are used by Geode but not listed in the file should be added

This PR addresses the first three points. Also, I have transformed the document to markdown, which is more friendly to edit than html, and it is the current Geode documentation format.

### CODE REVIEW

**Comment by alb3rtobr** [comment]
Moving the PR to "ready for review". Acceptance tests failed due to a flaky test case and Stress tests failed due to they are also failing in develop branch (I added a fix for that in https://github.com/apache/geode/pull/6182 ).

My idea is keep the ticket open after merging this PR, to continue adding missing properties to the list.

**Review by DonalEvans — APPROVED** [review]
This is a really excellent improvement, great work!

**Review by bschuchardt — APPROVED** [review]
the changes to my CODEOWNERS files look good

**Comment by DonalEvans** [comment]
For clarity, @davebarnes97 and @karensmolermiller, while this PR introduces a .md file containing documentation, it's not user-facing or part of the general Geode docs, just an internal file for developer reference.

**Comment by davebarnes97** [comment]
> For clarity, @davebarnes97 and @karensmolermiller, while this PR introduces a .md file containing documentation, it's not user-facing or part of the general Geode docs, just an internal file for developer reference.

My mistake -- thanks for clarifying. I'll delete our names from the reviewers list.

**Comment by alb3rtobr** [comment]
I guess @davebarnes97 closed the PR by mistake. Is it possible to open it again?

**Review by kirklund — APPROVED** [review]

**Review by gesterzhou — APPROVED** [review]

**Review by nabarunnag — APPROVED** [review]

**Comment by alb3rtobr** [comment]
Thanks for the reviews! Could someone merge this PR please? I dont have permissions to do it. Thanks!

**Comment by alb3rtobr** [comment]
Thanks @albertogpz but Im afraid you closed the PR instead of merge it :)

**Comment by albertogpz** [comment]
> Thanks @albertogpz but Im afraid you closed the PR instead of merge it :)

Sorry! Let's see if I did it right the second time ;-)

**Pull request merged**
