### PR TITLE
bump dependency versions

### PR DESCRIPTION
**Pull request by metatype**
Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [X] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [X] Is your initial contribution a single, squashed commit?

- [X] Does `gradlew build` run cleanly?

- [N/A] Have you written or updated unit tests to verify your changes?

- [N/A] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, check Concourse for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

### CODE REVIEW

**Comment by metatype** [comment]
Leaving Mockito at v0.23.x since later versions cause OOM in `HARegionQueueIntegrationTest`.

**Comment by pivotal-jbarrett** [comment]
@metatype I’d ask that you open a JIRA to fix this test and upgrade Mockito.

**Comment by metatype** [comment]
Also backing out the Jedis upgrade.

**Comment by metatype** [comment]
> @metatype I’d ask that you open a JIRA to fix this test and upgrade Mockito.

See GEODE-6590.

**Comment by onichols-pivotal** [comment]
this received a passing review...please rebase to latest develop so checks can re-run

**Comment by onichols-pivotal** [comment]
This PR appears to have been abandoned.  It will be closed in 72 hours if there is no further activity.

**Comment by onichols-pivotal** [comment]
closed due to inactivity

**Pull request closed without merging**
