### PR TITLE
GEODE-9517: Replace JUnit assertions with AssertJ in geode-assembly

### PR DESCRIPTION
**Pull request by DonalEvans**
Authored-by: Donal Evans <doevans@vmware.com>

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [x] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [x] Is your initial contribution a single, squashed commit?

- [x] Does `gradlew build` run cleanly?

- [N/A] Have you written or updated unit tests to verify your changes?

- [N/A] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### CODE REVIEW

**Review by demery-pivotal — COMMENTED** [review]
In a test with multiple assertions, or where the thing being asserted isn't obvious from the name of the test, consider adding an `as(...)` clause to make the failure message more informative.

**Comment by DonalEvans** [comment]
> In a test with multiple assertions, or where the thing being asserted isn't obvious from the name of the test, consider adding an `as(...)` clause to make the failure message more informative.

I had originally intended to keep these changes to be just a simple automatic refactor using the Assertions2Assert2 IntelliJ plugin, but since I've also reworked some of the assertions to be more sensible, I guess it makes sense to do a proper job of it and improve the failure messages as well. I'll get another commit with those changes up when I have the time.

**Comment by onichols-pivotal** [comment]
this PR appears to be abandoned, can it be closed?

**Comment by DonalEvans** [comment]
> this PR appears to be abandoned, can it be closed?

Yeah, I guess my hope that I'd find the time to work on this some more was optimistic to the point of foolishness.

**Pull request closed without merging**
