### PR TITLE
GEODE-9226: Refactor StartMemberUtils.resolveWorkingDir

### PR DESCRIPTION
**Pull request by alb3rtobr**
`StartMemberUtils` contains utility methods used by `StartLocatorCommand` & `StartServerCommand`.

One of them is `resolveWorkingDir` which returns the working directory to be used by the member. Part of the logic of this procedure is placed outside the function:
```
workingDirectory = StartMemberUtils.resolveWorkingDir(workingDirectory == null ? null : new File(workingDirectory), new File(memberName));
```
This causes that tests of that function need to create an instance of `StartLocatorCommand` & `StartServerCommand` classes.
And this has two negative consequences:

* When a new startup parameter is added to locators and/or server, the tests of `resolveWorkingDir` have to be modified.
* Tests are duplicated: there is a test class for every class using `resolveWorkingDir` (`StartLocatorCommandWorkingDirectoryTest` & `StartServerCommandWorkingDirectoryTest`).

### CODE REVIEW

**Review by rhoughton-pivot — APPROVED** [review]

**Review by dickcav — APPROVED** [review]

**Review by onichols-pivotal — APPROVED** [review]

**Review by mhansonp — APPROVED** [review]

**Comment by onichols-pivotal** [comment]
this looks ready to merge...if more changes coming, please convert to draft until it's ready

**Comment by alb3rtobr** [comment]
> this looks ready to merge...if more changes coming, please convert to draft until it's ready

The code is ready. Checks failed due to flaky tests. I have just added an empty commit to launch CI so I can merge this PR with checks passed.

**Review by jinmeiliao — APPROVED** [review]

**Comment by onichols-pivotal** [comment]
> > this looks ready to merge...if more changes coming, please convert to draft until it's ready
> 
> The code is ready. Checks failed due to flaky tests. I have just added an empty commit to launch CI so I can merge this PR with checks passed.

Hey @alb3rtobr thanks for endeavoring to have all checks green before merging!  _This week_ however it's likely that DistributedTestOpenJDK8 may not readily pass.  If the only failures are in DistributedTestOpenJDK8 and match known flaky tests identified by the latest [mass test report](https://concourse.apachegeode-ci.info/teams/main/pipelines/apache-develop-mass-test-run/jobs/create-mass-test-run-report/builds/13#L60659893:67), we can consider that good enough to merge.

**Comment by alb3rtobr** [comment]
Thanks for the info @onichols-pivotal . While I was waiting for the green light, a conflict was introduced in develop so I have just rebased the PR. Hopefully it will be the last change. :crossed_fingers:

**Review by gaussianrecurrence — APPROVED** [review]

**Pull request merged**
