### PR TITLE
Feature/geode 2217

### PR DESCRIPTION
**Pull request by dalyssakim**
JIRA : https://issues.apache.org/jira/browse/GEODE-2217

Let me know if we want to change the parameter descriptions.

### CODE REVIEW

**Comment by kirklund** [comment]
The Travis-CI failures are the NPEs that Darrel's change introduced. He reverted his change so that should resolve these failures.

**Comment by kirklund** [comment]
@dalyssakim Can you please do a git fetch and rebase your branch on develop? That should trigger the travis-ci again and pick up the fix that Darrel committed. Thanks!

**Comment by jhuynh1** [comment]
I pulled the changes and it built fine.  I collapsed and edited the commit messages to match how geode commits generally look and made a minor tweak to the wording on one parameter.  This is now in the develop branch of Geode.  Thanks (again) for the contribution!

**Comment by dalyssakim** [comment]
Thank you so much ! I will make sure I follow geode commits next time :) !

**Pull request closed without merging**
